force-app/main/default/objects/Admin_Setting__c/Admin_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Admin Setting</label>
</CustomObject>

force-app/main/default/objects/Admin_Setting__c/fields/Credit_Check_Email_template__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check_Email_template__c</fullName>
    <label>Credit Check Email template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Admin_Setting__c/fields/Credit_Check_Emails__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check_Emails__c</fullName>
    <label>Credit Check Emails</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tier_Approvers__c/Tier_Approvers__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting used to Define valid Email &amp; valid Email template for tier approval on Update Tier button for account object</description>
    <label>Tier Approvers</label>
</CustomObject>

force-app/main/default/objects/Tier_Approvers__c/fields/Emails__c.field-meta.xml
<CustomField>
    <fullName>Emails__c</fullName>
    <label>Emails</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tier_Approvers__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Country_Group__c.field-meta.xml
<CustomField>
    <fullName>Country_Group__c</fullName>
    <label>Country Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFRICA</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>Baltics</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BENEFRUX</fullName>
                <isActive>false</isActive>
                <label>BENEFRUX</label>
            </value>
            <value>
                <fullName>CEE</fullName>
                <isActive>false</isActive>
                <label>CEE</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IB</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>JAPAC (all other)</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MENA</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NL/BE</fullName>
                <isActive>false</isActive>
                <label>NL/BE</label>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SG/Japan/South Korea</fullName>
                <label>SG/Japan/South Korea (inact)</label>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountRequestTier.cls
/* 
 * Name   : AccountRequestTier 
 * Author       : Andrei Pruzan
 * Description   : Class Used to set info for Tier Update & credit check 
 * Maintenance History: 
 * 5/24/2017  - Created
 * 8/9/2017 - add logic in save action for credit check
*/
public with sharing class AccountRequestTier {
    public Account accountForEdit;
    public AccountRequestTier(ApexPages.StandardController con){
        accountForEdit = (Account) con.getRecord();
    }
    
    public PageReference SaveAction() {
        Map<String, Tier_Approvers__c> m_approvers = Tier_Approvers__c.getAll();
        User currentUser = [SELECT ID,Country_Group__c  FROM  User WHERE Id =: Userinfo.GetUserID()];
        String emails = null;
        String templateId = null;
        if (m_approvers.get(currentUser.Country_Group__c) != null){
            emails = m_approvers.get(currentUser.Country_Group__c).Emails__c;
            templateId = m_approvers.get(currentUser.Country_Group__c).Template__c;
        }
        else {
            emails = m_approvers.get('ALL').Emails__c;
            templateId = m_approvers.get('ALL').Template__c;
        }
        Admin_Setting__c setting = Admin_Setting__c.getOrgDefaults();
        if (ApexPages.currentPage().getUrl().containsIgnoreCase(Page.AccountCreditCheck.getUrl())) {
            emails = setting.Credit_Check_Emails__c;
            templateId = setting.Credit_Check_Email_template__c;
        }
        update accountForEdit;
        return new PageReference('/_ui/core/email/author/EmailAuthor?p3_lkid='+accountForEdit.Id+'&retURL=/'+accountForEdit.Id+'&template_id='+templateId+'&p24='+ emails);
    }
}