force-app/main/default/objects/Case/fields/Billing_title__c.field-meta.xml
<CustomField>
    <fullName>Billing_title__c</fullName>
    <label>Billing title</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoicing_Period_From__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Period_From__c</fullName>
    <label>Invoicing Period From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoicing_Period_To__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Period_To__c</fullName>
    <label>Invoicing Period To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Platform_ID__c.field-meta.xml
<CustomField>
    <fullName>Platform_ID__c</fullName>
    <label>Platform ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <formula>Contract__r.Template__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Platform_Account_Creation.recordType-meta.xml
<RecordType>
    <fullName>Platform_Account_Creation</fullName>
    <active>true</active>
    <businessProcess>Platform Account Process</businessProcess>
    <description>In order to create Platform Account, you need to open Case for Deal Desk</description>
    <label>TPAS/DSP ID</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/Platform_ID__c.object-meta.xml
<CustomObject>
    <description>Defines Adform Platform ID type and actual number. For billing usage data identification.</description>
    <label>Platform ID</label>
    <nameField>
        <displayFormat>PI-{0000000}</displayFormat>
        <label>Platform ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_ID__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Platform_IDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <label>Account ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/fields/Billing_Title__c.field-meta.xml
<CustomField>
    <fullName>Billing_Title__c</fullName>
    <externalId>true</externalId>
    <label>Billing Title</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>Legal office of the Sales person</description>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amsterdam</fullName>
            </value>
            <value>
                <fullName>Antwerpen</fullName>
            </value>
            <value>
                <fullName>Copenhagen</fullName>
            </value>
            <value>
                <fullName>Dusseldorf</fullName>
            </value>
            <value>
                <fullName>Hamburg</fullName>
            </value>
            <value>
                <fullName>Helsinki</fullName>
            </value>
            <value>
                <fullName>Istanbul</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
            <value>
                <fullName>Milan</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>Oslo</fullName>
            </value>
            <value>
                <fullName>Prague</fullName>
            </value>
            <value>
                <fullName>Stockholm</fullName>
            </value>
            <value>
                <fullName>Vilnius</fullName>
            </value>
            <value>
                <fullName>Warsaw</fullName>
            </value>
            <value>
                <fullName>Minsk</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Johannesburg</fullName>
            </value>
            <value>
                <fullName>Chicago</fullName>
            </value>
            <value>
                <fullName>Vienna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
public class CaseTriggerHandler {

    private boolean m_isExecuting = false;
    private integer BatchSize = 0;

    public CaseTriggerHandler(boolean isExecuting, integer size) {
        m_isExecuting = isExecuting;
        BatchSize = size;
    }

    public void OnBeforeInsert(Case[] newCases) {

    }

    public void OnAfterInsert(Case[] newCases) {
        List<Platform_ID__c> l_platforms = new List<Platform_ID__c>();
        Set<Id> s_caseId = new Set<Id>();
        Id caseRecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Platform_Account_Creation').getRecordTypeId();
        for(Case item : newCases){
            s_caseId.add(item.Id);
            if(item.Status != null && item.Status == 'Closed Resolved' && item.RecordTypeId == caseRecordTypeId){
                Platform_ID__c platform = new Platform_ID__c();
                platform.Account__c = item.AccountId;
                platform.Account_ID__c = item.Platform_ID__c;
                platform.Billing_Title__c = item.Billing_title__c;
                platform.CurrencyIsoCode = item.CurrencyIsoCode;
                platform.Start_Date__c = system.today();
                l_platforms.add(platform);
            }
        }
        //send email by office and recordType
        /*List<Case> l_cases = [SELECT Id, RecordTypeId, OwnerId FROM Case WHERE Id IN :s_caseId];
        List<Engagment_Request_List__c> l_engReq = [SELECT Id, Template__c, Name, Contact__c FROM Engagment_Request_List__c];
        for(Case c : l_cases){
            RecordType rt = [SELECT Id, Name FROM RecordType WHERE Id = :c.RecordTypeId LIMIT 1];
            if(rt.Name.equals('Engagement Request')){
                User owner = [SELECT Id, Office__c FROM User WHERE Id = :c.OwnerId LIMIT 1];
                for(Engagment_Request_List__c er : l_engReq ){
                    if(owner.Office__c.equals(er.Name)){
                        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                        mail.setSaveAsActivity(false);
                        mail.setTargetObjectId(er.Contact__c);
                        mail.setTemplateId(er.Template__c);
                        mail.setWhatId(c.Id);
                        Messaging.sendEmail(new Messaging.SingleEmailMessage [] { mail });
                    }
                }
            }
        }*/
        if(l_platforms.size() > 0){
            upsert l_platforms;
        }
    }


    public void OnBeforeUpdate(Case[] oldCases, Case[] updatedCases, Map<ID, Case> CaseMap, Map<ID, Case> oldCaseMap) {
        Date todayDate = Date.today();
        Integer NumberOfDays = date.daysInMonth(todayDate.year(), todayDate.month());
        Date startDate = todayDate.toStartOfMonth();
        Date endDate = date.newInstance(todayDate.year(), todayDate.month(), NumberOfDays);
        List<Contract> contracts = new List<Contract>();
        for(Case item: updatedCases) {
            if(item.Status == 'Production done and ready to bill' && oldCaseMap.get(item.Id).Status != 'Production done and ready to bill') {
                if (item.Invoicing_Period_From__c == null && item.Invoicing_Period_To__c == null) {
                    item.Invoicing_Period_From__c = startDate;
                    item.Invoicing_Period_To__c = endDate;
                }
                if (item.Contract__c != null) {
                    contracts.add(new Contract (Id=item.Contract__c, Status = 'Contract Closed'));
                }
            }
        }
        if(contracts.size() > 0){
            update contracts;
        }
    }

    public void OnAfterUpdate(Case[] oldCases, Case[] updatedCases, Map<ID, Case> CaseMap)  {
        Set<Id> s_accountIds = new Set<Id>();
        Set<Double> s_platformIds = new Set<Double>();
        for(Case item : updatedCases) {
            if (item.AccountId != null) {
                s_accountIds.add(item.AccountId);
            }
            if (item.Platform_ID__c != null) {
                s_platformIds.add(item.Platform_ID__c);
            }
        }
        List<Platform_ID__c> l_ids = [SELECT Id, Account__c, Account_ID__c, Name FROM Platform_ID__c WHERE Account__c IN :s_accountIds AND Account_ID__c IN :s_platformIds];
        Map<Double, Id> m_accounts = new Map<Double, Id>();
        for(Platform_ID__c item : l_ids) {
            m_accounts.put(item.Account_ID__c, item.Account__c);
        }
        Id caseRecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Platform_Account_Creation').getRecordTypeId();
        List<Platform_ID__c> l_platforms = new List<Platform_ID__c>();
        for(Case item : updatedCases) {
            if(item.Status != null && item.Status == 'Closed Resolved' && item.RecordTypeId == caseRecordTypeId){
                Id accountId = m_accounts.get(item.Platform_ID__c);
                if (accountId == null || (accountId != null && accountId != item.AccountId)){
                    Platform_ID__c platform = new Platform_ID__c();
                    platform.Account__c = item.AccountId;
                    platform.Account_ID__c = item.Platform_ID__c;
                    platform.Billing_Title__c = item.Billing_title__c;
                    platform.CurrencyIsoCode = item.CurrencyIsoCode;
                    platform.Start_Date__c = system.today();
                    l_platforms.add(platform);
                }
            }
        }
        if(l_platforms.size() > 0){
            upsert l_platforms;
        }
    }



    public void OnBeforeDelete(Case[] CasesToDelete, Map<ID, Case> CaseMap) {

    }

    public void OnAfterDelete(Case[] deletedCases, Map<ID, Case> CaseMap)   {
    }



    public void OnUndelete(Case[] restoredCases) { }

    public boolean IsTriggerContext {
        get { return m_isExecuting; }
    }

    public boolean IsVisualforcePageContext {
        get { return !IsTriggerContext; }
    }

    public boolean IsWebServiceContext {
        get { return !IsTriggerContext; }
    }

    public boolean IsExecuteAnonymousContext {
        get { return !IsTriggerContext; }
    }

}