force-app/main/default/objects/Platform_ID__c/Platform_ID__c.object-meta.xml
<CustomObject>
    <description>Defines Adform Platform ID type and actual number. For billing usage data identification.</description>
    <label>Platform ID</label>
    <nameField>
        <displayFormat>PI-{0000000}</displayFormat>
        <label>Platform ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_ID__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Platform_IDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/fields/Billing_Title__c.field-meta.xml
<CustomField>
    <fullName>Billing_Title__c</fullName>
    <externalId>true</externalId>
    <label>Billing Title</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BillingTitleSearchResultsController.cls
/*
    * Name        : BillingTitleSearchResultsController
    * Author        : Dmitrij Marcinkevic
    * Description   : Class displays all Accounts with such Billing Title
    * Maintenance History:
    * 2018-06-27
*/
public with sharing class BillingTitleSearchResultsController {
    public List<Account> l_accounts { get; set; }
    public String searchValue { get; set; }
    public BillingTitleSearchResultsController(){
        searchValue = ApexPages.currentPage().getParameters().get('sbstr');
        l_accounts = getAccounts(searchValue);
    }

    private List<Account> getAccounts(String searchValue){
        List<Schema.FieldSetMember> l_fields = SObjectType.Account.FieldSets.foundAccounts.getFields();
        String query = 'SELECT ';
        for(Schema.FieldSetMember field : l_fields){
            query += field.getFieldPath() + ', ';
        }
        query = query.trim();
        query = query.substring(0, query.length() - 1);
        query += ' FROM Account WHERE Id IN (SELECT Account__c FROM Platform_ID__c WHERE Billing_Title__c LIKE \'%' + searchValue + '%\' )';
        List<Account> l_accounts = Database.query(query);
        return l_accounts;
    }
    
    public PageReference searchAction() {
        l_accounts = getAccounts(searchValue);
        return null;
    }
    
    public PageReference homeRedirect() {
        return new PageReference('/home/home.jsp');
    }
}