force-app/main/default/objects/Billing_Resource__c/Billing_Resource__c.object-meta.xml
<CustomObject>
    <label>Billing Resource</label>
    <nameField>
        <label>Billing Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Resource__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Platform_ID__c.field-meta.xml
<CustomField>
    <fullName>Platform_ID__c</fullName>
    <label>Platform ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/Contract_Price__c.object-meta.xml
<CustomObject>
    <label>Contract Price</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Contract Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Price__c/fields/Billing_Resource__c.field-meta.xml
<CustomField>
    <fullName>Billing_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Resource</label>
    <referenceTo>Billing_Resource__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Invoice_Template__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Template</label>
    <referenceTo>Invoice_Template__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Price</label>
    <referenceTo>Product_Price__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/Invoice_Template__c.object-meta.xml
<CustomObject>
    <label>Invoice Template</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Invoice Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Template__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/Platform_ID__c.object-meta.xml
<CustomObject>
    <description>Defines Adform Platform ID type and actual number. For billing usage data identification.</description>
    <label>Platform ID</label>
    <nameField>
        <displayFormat>PI-{0000000}</displayFormat>
        <label>Platform ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Billing_Resource__c.field-meta.xml
<CustomField>
    <fullName>Billing_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Resource</label>
    <referenceTo>Billing_Resource__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Invoice_Template__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Template__c</fullName>
    <label>Invoice Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Master Data</fullName>
            </value>
            <value>
                <fullName>RTB</fullName>
            </value>
            <value>
                <fullName>SE Integrations</fullName>
            </value>
            <value>
                <fullName>TPAS</fullName>
            </value>
            <value>
                <fullName>Pixel Apps</fullName>
            </value>
            <value>
                <fullName>Creative service</fullName>
            </value>
            <value>
                <fullName>Minimum Fee</fullName>
            </value>
            <value>
                <fullName>INTERNAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Price__c/Product_Price__c.object-meta.xml
<CustomObject>
    <label>Product Price</label>
    <nameField>
        <label>Product Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ImportData_Test.cls
/*
    * Name        : ImportData_Test
    * Author        : Dmitrij Marcinkevic
    * Description   : Class tests imported data from ImportData class
    * Maintenance History:
    * 12/06/2018
*/
@IsTest(SeeAllData = false)
public class ImportData_Test {
    @testSetup static void initData() {
        ImportData.initData();
    }

    static testmethod void getImportedDataCount_test (){
        List<Account> l_accounts = [SELECT Id FROM Account];
        System.assert(l_accounts.size() >= 20);
        /*List<Lead> l_leads = [SELECT Id FROM Lead];
        System.assert(l_leads.size() >= 20);
        List<Contact> l_contacts = [SELECT Id FROM Contact];
        System.assert(l_contacts.size() >= 120);
        List<Platform_ID__c> l_platformIds = [SELECT Id FROM Platform_ID__c];
        System.assert(l_platformIds.size() >= 60);
        List<Opportunity> l_opportunity = [SELECT Id FROM Opportunity];
        System.assert(l_opportunity.size() >= 40);
        List<Product_Group__c> l_productGroups = [SELECT Id FROM Product_Group__c];
        System.assert(l_productGroups.size() >= 2);
        List<Billing_Resource__c> l_billingResources = [SELECT Id FROM Billing_Resource__c];
        System.assert(l_billingResources.size() >= 1);
        List<Product__c> l_products = [SELECT Id FROM Product__c];
        System.assert(l_products.size() >= 4);
        List<Product_Price__c> l_productPrices = [SELECT Id FROM Product_Price__c];
        System.assert(l_productPrices.size() >= 12);
        List<Contract> l_contracts = [SELECT Id FROM Contract];
        System.assert(l_contracts.size() > 0);
        List<Invoice_Template__c> l_invoiceTemplate = [SELECT Id FROM Invoice_Template__c];
        System.assert(l_invoiceTemplate.size() >= 40);
        List<Contract_Price__c> l_contractPrices = [SELECT Id FROM Contract_Price__c];
        System.assert(l_contractPrices.size() >= 80);
        List<Case> l_cases = [SELECT Id FROM Case];
        System.assert(l_cases.size() >= 60);*/
    }
}