force-app/main/default/objects/Bonus_Target__c/Bonus_Target__c.object-meta.xml
<CustomObject>
    <description>Object for storing bonus target information</description>
    <label>Bonus Target</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Bonus target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bonus_Target__c/fields/April__c.field-meta.xml
<CustomField>
    <fullName>April__c</fullName>
    <label>April</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/August__c.field-meta.xml
<CustomField>
    <fullName>August__c</fullName>
    <description>% for target split for new year</description>
    <label>August</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Bad_debts__c.field-meta.xml
<CustomField>
    <fullName>Bad_debts__c</fullName>
    <description>Bad debts</description>
    <label>Bad debts</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Bonus_Currency__c.field-meta.xml
<CustomField>
    <fullName>Bonus_Currency__c</fullName>
    <label>Bonus Currency</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/BONUS_OTE_in_l_c__c.field-meta.xml
<CustomField>
    <fullName>BONUS_OTE_in_l_c__c</fullName>
    <label>BONUS OTE in l.c.</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Bonus_split__c.field-meta.xml
<CustomField>
    <fullName>Bonus_split__c</fullName>
    <label>Bonus split, %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comment</description>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Current_Year_Target__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Target__c</fullName>
    <label>Current Year Target</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Customer type</description>
    <label>Customer Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/December__c.field-meta.xml
<CustomField>
    <fullName>December__c</fullName>
    <description>% for target split for new year</description>
    <label>December</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>Employee For Upload field used in upload action</description>
    <label>Employee For Upload</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Employee_user__c.field-meta.xml
<CustomField>
    <fullName>Employee_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee user</description>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bonus_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/February__c.field-meta.xml
<CustomField>
    <fullName>February__c</fullName>
    <label>February</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Guaranteed_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Guaranteed_Period_End__c</fullName>
    <description>Guaranteed Period End</description>
    <label>Guaranteed Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Guaranteed_Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Guaranteed_Period_Start__c</fullName>
    <description>Guaranteed Period Start</description>
    <label>Guaranteed Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/January__c.field-meta.xml
<CustomField>
    <fullName>January__c</fullName>
    <description>% for target split for new year</description>
    <label>January</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/July__c.field-meta.xml
<CustomField>
    <fullName>July__c</fullName>
    <description>% for target split for new year</description>
    <label>July</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/June__c.field-meta.xml
<CustomField>
    <fullName>June__c</fullName>
    <description>% for target split for new year</description>
    <label>June</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_April__c.field-meta.xml
<CustomField>
    <fullName>LY_April__c</fullName>
    <label>LY April</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_August__c.field-meta.xml
<CustomField>
    <fullName>LY_August__c</fullName>
    <label>LY August</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_December__c.field-meta.xml
<CustomField>
    <fullName>LY_December__c</fullName>
    <label>LY December</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_February__c.field-meta.xml
<CustomField>
    <fullName>LY_February__c</fullName>
    <label>LY February</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_January__c.field-meta.xml
<CustomField>
    <fullName>LY_January__c</fullName>
    <label>LY January</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_July__c.field-meta.xml
<CustomField>
    <fullName>LY_July__c</fullName>
    <label>LY July</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_June__c.field-meta.xml
<CustomField>
    <fullName>LY_June__c</fullName>
    <label>LY June</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_March__c.field-meta.xml
<CustomField>
    <fullName>LY_March__c</fullName>
    <label>LY March</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_May__c.field-meta.xml
<CustomField>
    <fullName>LY_May__c</fullName>
    <label>LY May</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_November__c.field-meta.xml
<CustomField>
    <fullName>LY_November__c</fullName>
    <label>LY November</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_October__c.field-meta.xml
<CustomField>
    <fullName>LY_October__c</fullName>
    <label>LY October</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/LY_September__c.field-meta.xml
<CustomField>
    <fullName>LY_September__c</fullName>
    <label>LY September</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <description>Manager for Upload used to set text value for user name and after that system will find a valid manager</description>
    <label>Manager For Upload</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Manager_User__c.field-meta.xml
<CustomField>
    <fullName>Manager_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manager username</description>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bonus_Targets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/March__c.field-meta.xml
<CustomField>
    <fullName>March__c</fullName>
    <label>March</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <label>May</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/November__c.field-meta.xml
<CustomField>
    <fullName>November__c</fullName>
    <description>% for target split for new year</description>
    <label>November</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/October__c.field-meta.xml
<CustomField>
    <fullName>October__c</fullName>
    <description>% for target split for new year</description>
    <label>October</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>Office</description>
    <label>Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Previous_Year_Actual__c.field-meta.xml
<CustomField>
    <fullName>Previous_Year_Actual__c</fullName>
    <label>Previous Year Actual</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product</description>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/September__c.field-meta.xml
<CustomField>
    <fullName>September__c</fullName>
    <description>% for target split for new year</description>
    <label>September</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/User/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>Legal office of the Sales person</description>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amsterdam</fullName>
            </value>
            <value>
                <fullName>Antwerpen</fullName>
            </value>
            <value>
                <fullName>Copenhagen</fullName>
            </value>
            <value>
                <fullName>Dusseldorf</fullName>
            </value>
            <value>
                <fullName>Hamburg</fullName>
            </value>
            <value>
                <fullName>Helsinki</fullName>
            </value>
            <value>
                <fullName>Istanbul</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
            <value>
                <fullName>Milan</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>Oslo</fullName>
            </value>
            <value>
                <fullName>Prague</fullName>
            </value>
            <value>
                <fullName>Stockholm</fullName>
            </value>
            <value>
                <fullName>Vilnius</fullName>
            </value>
            <value>
                <fullName>Warsaw</fullName>
            </value>
            <value>
                <fullName>Minsk</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Johannesburg</fullName>
            </value>
            <value>
                <fullName>Chicago</fullName>
            </value>
            <value>
                <fullName>Vienna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target (EUR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BonusTarget.cls
public with sharing class BonusTarget {
    public List<Bonus_Target__c> l_target { get; set; }
    public User currentUser { get; set ;}
    
    public BonusTarget() {
        l_target = [SELECT April__c,August__c,Bad_debts__c,Bonus_Currency__c,BONUS_OTE_in_l_c__c,Bonus_split__c,Comment__c,Country__c,CreatedById,
                    CreatedDate,CurrencyIsoCode,Current_Year_Target__c,Customer_Type__c,December__c,Employee_user__c,Employee__c,February__c,
                    Guaranteed_Period_End__c,Guaranteed_Period_Start__c,Id,IsDeleted,January__c,July__c,June__c,LastModifiedById,LastModifiedDate,
                    LY_April__c,LY_August__c,LY_December__c,LY_February__c,LY_January__c,LY_July__c,LY_June__c,
                    LY_March__c,LY_May__c,LY_November__c,LY_October__c,LY_September__c,Manager_User__c,Manager__c,March__c,May__c,
                    Name,November__c,October__c,Office__c,OwnerId,Previous_Year_Actual__c,Product__c,September__c,Stage__c,Status__c,
                    SVP_User__c,SVP__c,SystemModstamp,Target_currency__c,Target_ID__c,Target__c,Year_for_target__c,YoY__c,
                    LY_Actual__c, Target_Q1__c, Target_Q2__c, Target_Q3__c, Target_Q4__c FROM Bonus_Target__c WHERE Stage__c = 'Employee' AND Employee_user__c =: UserInfo.getUserId() AND Status__c = 'Active'];
        
        currentUser = [SELECT ID, FirstName, Lastname, ManagerId FROM User WHERE  ID =:UserInfo.getUserId()];
       
    }

    
}