force-app/main/default/objects/Bonus_Target__c/Bonus_Target__c.object-meta.xml
<CustomObject>
    <description>Object for storing bonus target information</description>
    <label>Bonus Target</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Bonus target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bonus_Target__c/fields/Employee_user__c.field-meta.xml
<CustomField>
    <fullName>Employee_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee user</description>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bonus_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Manager_User__c.field-meta.xml
<CustomField>
    <fullName>Manager_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manager username</description>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bonus_Targets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>SVP</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Employee Accept</fullName>
            </value>
            <value>
                <fullName>All Manager approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bonus_Target__c/fields/SVP_User__c.field-meta.xml
<CustomField>
    <fullName>SVP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SVP User in system</description>
    <label>Hige Level</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bonus_Targets2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BT_BonusTarget_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=false)
private class BT_BonusTarget_Test{
    // Unit test setup. Create all required data for testing
    @testSetup static void initData() {
        Bonus_Target__c bonusTarget = new Bonus_Target__c(Stage__c = 'Employee' , Employee_user__c = UserInfo.getUserId() , Status__c = 'Active');
        insert bonusTarget;
    }
    /* 
        test bonus target view
    */
    static testmethod void test_view() {
        Test.startTest();
            BonusTarget controller = new BonusTarget();
        Test.stopTest();
    }
    /* 
        test bonus target trigger
    */
    static testmethod void test_update() {
        Test.startTest();
            Bonus_Target__c bonusTarget = [select id,SVP_User__c,Manager_User__c  from Bonus_Target__c];
            bonusTarget.SVP_User__c = UserInfo.getUserId();
            //bonusTarget.Stage__c = 'SVP';
            update bonusTarget;
             bonusTarget.Manager_User__c = UserInfo.getUserId();
             //bonusTarget.Stage__c = 'Manager';
            update bonusTarget;
        Test.stopTest();
    }
    /* 
        test bonus target view page
    */
    static testmethod void test_action_page() {
        Test.startTest();
            Bonus_Target__c bonusTarget = [select id,SVP_User__c,Manager_User__c  from Bonus_Target__c];
            bonusTarget.SVP_User__c = UserInfo.getUserId();
            //bonusTarget.Stage__c = 'SVP';
            update bonusTarget;
             bonusTarget.Manager_User__c = UserInfo.getUserId();
             //bonusTarget.Stage__c = 'Manager';
            update bonusTarget;
        Test.stopTest();
    }
}