force-app/main/default/objects/Contract/fields/Invoice_details__c.field-meta.xml
<CustomField>
    <fullName>Invoice_details__c</fullName>
    <label>Invoice details</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Minimal (agency level)</fullName>
            </value>
            <value>
                <fullName>Medium (end client level)</fullName>
            </value>
            <value>
                <fullName>Maximum (campaign level)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Invoice_level__c.field-meta.xml
<CustomField>
    <fullName>Invoice_level__c</fullName>
    <label>Invoice level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>End Client</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Price__c/Contract_Price__c.object-meta.xml
<CustomObject>
    <label>Contract Price</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Contract Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Price__c/fields/Invoice_Template__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Template</label>
    <referenceTo>Invoice_Template__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Price</label>
    <referenceTo>Product_Price__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/ProductCustom__c.field-meta.xml
<CustomField>
    <fullName>ProductCustom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/Invoice_Template__c.object-meta.xml
<CustomObject>
    <label>Invoice Template</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Invoice Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Template__c/fields/Fees_Calculation_model__c.field-meta.xml
<CustomField>
    <fullName>Fees_Calculation_model__c</fullName>
    <label>Fees Calculation model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pricing_Model__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Included Fees</fullName>
            </value>
            <value>
                <fullName>On Top Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Invoice_Details__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Details__c</fullName>
    <label>Invoice Details</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Invoice_Level__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Minimal (agency level)</fullName>
            </value>
            <value>
                <fullName>Medium (end client level)</fullName>
            </value>
            <value>
                <fullName>Maximum (campaign level)</fullName>
                <default>true</default>
                <label>Maximum (campaign level)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Invoice_Level__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Level__c</fullName>
    <label>Invoice Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
                <default>true</default>
                <label>Agency</label>
            </value>
            <value>
                <fullName>End Client</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Payment_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms_Code__c</fullName>
    <label>Payment Terms Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>L0</fullName>
            </value>
            <value>
                <fullName>L1</fullName>
            </value>
            <value>
                <fullName>L10</fullName>
            </value>
            <value>
                <fullName>L15</fullName>
            </value>
            <value>
                <fullName>L20</fullName>
            </value>
            <value>
                <fullName>L25</fullName>
            </value>
            <value>
                <fullName>L30</fullName>
            </value>
            <value>
                <fullName>L60</fullName>
            </value>
            <value>
                <fullName>L90</fullName>
            </value>
            <value>
                <fullName>M0</fullName>
            </value>
            <value>
                <fullName>M10</fullName>
            </value>
            <value>
                <fullName>M105</fullName>
            </value>
            <value>
                <fullName>M11</fullName>
            </value>
            <value>
                <fullName>M120</fullName>
            </value>
            <value>
                <fullName>M13</fullName>
            </value>
            <value>
                <fullName>M14</fullName>
            </value>
            <value>
                <fullName>M15</fullName>
            </value>
            <value>
                <fullName>M18</fullName>
            </value>
            <value>
                <fullName>M20</fullName>
            </value>
            <value>
                <fullName>M21</fullName>
            </value>
            <value>
                <fullName>M22</fullName>
            </value>
            <value>
                <fullName>M25</fullName>
            </value>
            <value>
                <fullName>M28</fullName>
            </value>
            <value>
                <fullName>M3</fullName>
            </value>
            <value>
                <fullName>M30</fullName>
            </value>
            <value>
                <fullName>M33</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Pricing_Model__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Model__c</fullName>
    <label>Pricing Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>File_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Activity Based</fullName>
            </value>
            <value>
                <fullName>Fixed Fee</fullName>
            </value>
            <value>
                <fullName>Net Amount</fullName>
            </value>
            <value>
                <fullName>Pure media + Data</fullName>
            </value>
            <value>
                <fullName>Gross Platform Spend</fullName>
            </value>
            <value>
                <fullName>Pure Media</fullName>
            </value>
            <value>
                <fullName>Net Amount + RTB</fullName>
            </value>
            <value>
                <fullName>Net Amount + RTB - TPB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Invoice_Details__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Details__c</fullName>
    <label>Invoice Details</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minimal (agency level)</fullName>
            </value>
            <value>
                <fullName>Medium (end client level)</fullName>
            </value>
            <value>
                <fullName>Maximum (campaign level)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Invoice_Level__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Level__c</fullName>
    <label>Invoice Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>End Client</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Invoice_Template__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Template__c</fullName>
    <label>Invoice Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Master Data</fullName>
            </value>
            <value>
                <fullName>RTB</fullName>
            </value>
            <value>
                <fullName>SE Integrations</fullName>
            </value>
            <value>
                <fullName>TPAS</fullName>
            </value>
            <value>
                <fullName>Pixel Apps</fullName>
            </value>
            <value>
                <fullName>Creative service</fullName>
            </value>
            <value>
                <fullName>Minimum Fee</fullName>
            </value>
            <value>
                <fullName>INTERNAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Price__c/Product_Price__c.object-meta.xml
<CustomObject>
    <label>Product Price</label>
    <nameField>
        <label>Product Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Text_Price__c.field-meta.xml
<CustomField>
    <fullName>Text_Price__c</fullName>
    <label>Text Price</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RC_InvoiceTemplatesHTMLController.cls
public class RC_InvoiceTemplatesHTMLController {
    
  public Id ContractId;
 
  public String currencyStr { get; set; }
  public void setContractId (String s) {
    contractId = s;
  }
    
  public String getContractId() {
    return contractId;
  } 
  public List<Invoice_Template__c> getTemplates(){
      Contract contract = [SELECT ID,CurrencyIsoCode FROM Contract WHERE Id =: contractId];
      List<Invoice_Template__c> l_templates =   [SELECT ID, NAME, Product_Group__r.Label__c, Pricing_Model__c, Payment_Terms_Code__c, Invoice_Details__c, Invoice_Level__c, Fees_Calculation_model__c,
                        (SELECT ID, NAME,ProductCustom__r.Name,Product_Price__r.Text_Price__c, ProductCustom__r.Measure__c ,Is_Price_lower__c, CurrencyIsoCode, Price__c , Price_Percent__c,Product_Price__r.Minimum_Price_Currency__c,
                        Product_Price__r.Minimum_Price_Percent__c, Main_Contract_Price__c FROM Contract_Prices__r WHERE Ending_Date__c  = null ORDER BY ProductCustom__r.Order__c), Is_Payment_Terms_Higher__c
                         FROM Invoice_Template__c WHERE Contract__c =:contractId  AND End_Date__c = null ORDER BY Product_Group__r.Order__c];
       currencyStr = contract.CurrencyIsoCode;
        for(Invoice_Template__c item : l_templates) {
            for(Contract_Price__c cp : item.Contract_Prices__r) {
                if(contract.CurrencyIsoCode != cp.CurrencyIsoCode  && cp.Price__c != null && cp.Price_Percent__c == null) {
                    currencyStr = cp.CurrencyIsoCode;
                    break;
                }
            }
        }
      return l_templates;
  }
}