force-app/main/default/objects/Contract/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Pricing Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activity Based</fullName>
            </value>
            <value>
                <fullName>Fixed Fee</fullName>
            </value>
            <value>
                <fullName>Net Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/RTB_options__c.field-meta.xml
<CustomField>
    <fullName>RTB_options__c</fullName>
    <label>RTB options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Fee</fullName>
                <default>true</default>
                <label>Standard Fee</label>
            </value>
            <value>
                <fullName>Trading Desc Fee</fullName>
            </value>
            <value>
                <fullName>Trading Desc Fee + Included fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Price__c/Contract_Price__c.object-meta.xml
<CustomObject>
    <label>Contract Price</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Contract Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Price__c/fields/Invoice_Template__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Template</label>
    <referenceTo>Invoice_Template__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Main_Contract_Price__c.field-meta.xml
<CustomField>
    <fullName>Main_Contract_Price__c</fullName>
    <description>This field filled by Multiple_Billing_Resource__c.Main_Billing_Resource__c</description>
    <label>Main Contract Price</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Price_Percent__c.field-meta.xml
<CustomField>
    <fullName>Price_Percent__c</fullName>
    <label>Price Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Price</label>
    <referenceTo>Product_Price__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/ProductCustom__c.field-meta.xml
<CustomField>
    <fullName>ProductCustom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/Invoice_Template__c.object-meta.xml
<CustomObject>
    <label>Invoice Template</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Invoice Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Template__c/fields/Fees_Calculation_model__c.field-meta.xml
<CustomField>
    <fullName>Fees_Calculation_model__c</fullName>
    <label>Fees Calculation model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pricing_Model__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Included Fees</fullName>
            </value>
            <value>
                <fullName>On Top Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Pricing_Model__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Model__c</fullName>
    <label>Pricing Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>File_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Activity Based</fullName>
            </value>
            <value>
                <fullName>Fixed Fee</fullName>
            </value>
            <value>
                <fullName>Net Amount</fullName>
            </value>
            <value>
                <fullName>Pure media + Data</fullName>
            </value>
            <value>
                <fullName>Gross Platform Spend</fullName>
            </value>
            <value>
                <fullName>Pure Media</fullName>
            </value>
            <value>
                <fullName>Net Amount + RTB</fullName>
            </value>
            <value>
                <fullName>Net Amount + RTB - TPB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Hide_Pricing_Model__c.field-meta.xml
<CustomField>
    <fullName>Hide_Pricing_Model__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Hide pricing model from pricing information export.</inlineHelpText>
    <label>Hide Pricing Model</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Measure__c.field-meta.xml
<CustomField>
    <fullName>Measure__c</fullName>
    <label>Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>%</fullName>
            </value>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>CPC</fullName>
            </value>
            <value>
                <fullName>% from RTB budget spend</fullName>
            </value>
            <value>
                <fullName>Fixed per app install</fullName>
            </value>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>Hour</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>% (adserving cost)</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>KB</fullName>
            </value>
            <value>
                <fullName>Imp</fullName>
            </value>
            <value>
                <fullName>CPM (incremental per MB)</fullName>
            </value>
            <value>
                <fullName>Thousand Impressions</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
            <value>
                <fullName>Thousand Impressions (incremental per each 1,000 KB above 3,000 KB)</fullName>
            </value>
            <value>
                <fullName>Search Engine Costs</fullName>
            </value>
            <value>
                <fullName>Click</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>TPAS fees</fullName>
            </value>
            <value>
                <fullName>TPAS and Third Party Tracking with Adform fees</fullName>
            </value>
            <value>
                <fullName>RTB Service Fee Units indicated above or CPM</fullName>
            </value>
            <value>
                <fullName>Banner Created</fullName>
            </value>
            <value>
                <fullName>Trading Desk Fee</fullName>
            </value>
            <value>
                <fullName>-</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Period_Of_Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Period_Of_Invoicing__c</fullName>
    <label>Period Of Invoicing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>On Campaign End</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Read_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check, if you want to disable service from editing.</inlineHelpText>
    <label>Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Hide_on_Print_View__c.field-meta.xml
<CustomField>
    <fullName>Hide_on_Print_View__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide on Print View</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Invoice_Template__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Template__c</fullName>
    <label>Invoice Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Master Data</fullName>
            </value>
            <value>
                <fullName>RTB</fullName>
            </value>
            <value>
                <fullName>SE Integrations</fullName>
            </value>
            <value>
                <fullName>TPAS</fullName>
            </value>
            <value>
                <fullName>Pixel Apps</fullName>
            </value>
            <value>
                <fullName>Creative service</fullName>
            </value>
            <value>
                <fullName>Minimum Fee</fullName>
            </value>
            <value>
                <fullName>INTERNAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Print_Out_Label__c.field-meta.xml
<CustomField>
    <fullName>Print_Out_Label__c</fullName>
    <label>Print Out Label</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/Product_Price__c.object-meta.xml
<CustomObject>
    <label>Product Price</label>
    <nameField>
        <label>Product Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Price_Percent__c.field-meta.xml
<CustomField>
    <fullName>Price_Percent__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Text_Price__c.field-meta.xml
<CustomField>
    <fullName>Text_Price__c</fullName>
    <label>Text Price</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RC_BMSAPriceController.cls
public with sharing class RC_BMSAPriceController {
    public List<Invoice_Template__c> l_templates { get; set; }
    public List<Contract_Price__c> l_contractPrices { get; set; }

    public String currencyStr { get; set; }
    public RC_BMSAPriceController(ApexPages.StandardController con){
        l_contractPrices = new List<Contract_Price__c>();
        if (Test.isRunningTest() == false) {
            con.addFields(new List<String>{'RTB_options__c','Invoice_Type__c', 'CurrencyIsoCode'});
        }
        Contract contract = (Contract) con.getRecord();
        Contract contractTemp = [SELECT ID, CurrencyIsoCode FROM Contract WHERE Id =: contract.Id];
        l_templates = [SELECT ID, NAME, Product_Group__r.Label__c, Product_Group__r.Name,Product_Group__r.Hide_on_Print_View__c ,Product_Group__r.Read_Only__c , Product_Group__r.Print_Out_Label__c, Fees_Calculation_model__c, Pricing_Model__c,
                        (SELECT ID, NAME, ProductCustom__r.Name, ProductCustom__r.Measure__c,Product_Price__r.Text_Price__c,
                        ProductCustom__r.Period_Of_Invoicing__c, CurrencyIsoCode, Price__c,
                        Price_Percent__c, Main_Contract_Price__c, ProductCustom__r.Hide_Pricing_Model__c, ProductCustom__r.Product_Group__r.Read_Only__c, Billing_Resource__r.Name FROM Contract_Prices__r ORDER BY ProductCustom__r.Order__c)
                        FROM Invoice_Template__c WHERE Contract__c =:contract.Id ORDER BY Product_Group__r.Order__c];
        currencyStr = contractTemp.CurrencyIsoCode;
        for(Invoice_Template__c item : l_templates) {
            for(Contract_Price__c cp : item.Contract_Prices__r) {
                if(cp.Billing_Resource__r.Name == '(DO NOT USE) Brand Safety Costs - DoubleVerify2'){
                    l_contractPrices.add(cp);
                }
                if( cp.Price__c != null && cp.Price_Percent__c == null && currencyStr != cp.CurrencyIsoCode && cp.ProductCustom__r.Hide_Pricing_Model__c == false && cp.ProductCustom__r.Product_Group__r.Read_Only__c == false) {
                    currencyStr = cp.CurrencyIsoCode;
                }
            }
        }
        for(Multiple_Billing_Resource__c mbr : [SELECT Id, Name, Product__c FROM Multiple_Billing_Resource__c WHERE Main_Billing_Resource__c = false]){
            for(Contract_Price__c cp : l_contractPrices){
                if(cp.ProductCustom__c == mbr.Product__c){
                    cp.Multiple_Billing_Resource_Name__c = mbr.Name;
                }
            }
        }
    }
}