force-app/main/default/objects/Account/fields/Account_Level__c.field-meta.xml
<CustomField>
    <fullName>Account_Level__c</fullName>
    <inlineHelpText>If Agency is owned by a Holding Group, enter the name of the governing Account in the Parent Account field below.</inlineHelpText>
    <label>Account Level</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Relationship_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Holding Company Group</fullName>
            </value>
            <value>
                <fullName>Holding Company Division</fullName>
            </value>
            <value>
                <fullName>Holding Company Agency</fullName>
            </value>
            <value>
                <fullName>Independent Agency</fullName>
            </value>
            <value>
                <fullName>Independent Publisher</fullName>
            </value>
            <value>
                <fullName>Ad Network</fullName>
            </value>
            <value>
                <fullName>Ad Tech</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Niche</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Approached</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Emails__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Emails__c</fullName>
    <label>Invoice Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registered_Number__c.field-meta.xml
<CustomField>
    <fullName>Registered_Number__c</fullName>
    <inlineHelpText>Please enter the registered number for Contract purposes.</inlineHelpText>
    <label>Registered Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Creative Agency</fullName>
            </value>
            <value>
                <fullName>Consultancy Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Standalone Agency</fullName>
            </value>
            <value>
                <fullName>Trading Desk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <inlineHelpText>Please enter the VAT Number for Contract prurposes</inlineHelpText>
    <label>VAT Number / Sales Tax</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Admin_Setting__c/Admin_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Admin Setting</label>
</CustomObject>

force-app/main/default/objects/Admin_Setting__c/fields/Billing_Emails__c.field-meta.xml
<CustomField>
    <fullName>Billing_Emails__c</fullName>
    <description>This field used to store emails separated by &quot;;&quot;. These emails will be used in Billing schedule job(send billing report).</description>
    <label>Billing Emails</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/BillingReport_Scheduler.cls
global class BillingReport_Scheduler implements Schedulable{
    // The excuteBatch method for scheduleing
    global void execute(SchedulableContext SC){
        Date lastMonthFirstDay = Date.today().addMonths(-1);
        List<Account> l_accouns = [SELECT Name, BillingStreet, BillingPostalCode, BillingCity, BillingCountry,
                                   Relationship_Type__c, Customer_Group_Name__c,Account_Level__c,Parent.Name, Owner.Name,
                                   CurrencyIsoCode, VAT_Number__c, Registered_Number__c, Id, Notes__c, Invoice_Emails__c, 
                                     CreatedDate FROM Account WHERE LastModifiedDate >= LAST_MONTH];
        Map <String, Schema.SObjectField> m_accountFields  =  Account.sObjectType.getDescribe().fields.getMap();
        String header ='';
        List<String> l_headerValues = new List<String>{'Is New', 'Account Name',
                                                        'Invoice Street',
                                                        'Invoice Zip/Postal Code',
                                                        'Invoice city',
                                                        'Invoice country',
                                                        'Account Type',
                                                        'Customer Group Name',
                                                        'Account Level',
                                                        'Parent Account',
                                                        'Account owner',
                                                        'Account Currency',
                                                        'VAT Number / Sales Tax',
                                                        'Registered Number',
                                                        'Account ID',
                                                        'Notes & Attachments',
                                                        'Invoice Email'};
        
        header = String.join(l_headerValues, ',')+'\n';
        String finalstr = header;
        String recordString = '';
        for(Account a: l_accouns) {
            String fieldStr = '';
            List<object> l_fieldValues = new List<object>();
            
            String isNew = 'Updated';
            if (a.CreatedDate >= lastMonthFirstDay) {
                isNew = 'New';
            }
            l_fieldValues.add('"'+isNew+'"');
            l_fieldValues.add('"'+a.Name+'"');
            l_fieldValues.add('"'+(a.BillingStreet != null ? a.BillingStreet : '')+'"');
            l_fieldValues.add('"'+(a.BillingPostalCode != null ? a.BillingPostalCode : '')+'"');
            l_fieldValues.add('"'+(a.BillingCity != null ? a.BillingCity : '')+'"');
            l_fieldValues.add('"'+(a.BillingCountry != null ? a.BillingCountry : '')+'"');
            l_fieldValues.add('"'+(a.Relationship_Type__c != null ? a.Relationship_Type__c : '')+'"');
            l_fieldValues.add('"'+(a.Customer_Group_Name__c != null ? a.Customer_Group_Name__c : '')+'"');
            l_fieldValues.add('"'+(a.Account_Level__c != null ? a.Account_Level__c : '')+'"');
            l_fieldValues.add('"'+(a.Parent.Name != null ? a.Parent.Name : '')+'"');
            l_fieldValues.add('"'+(a.Owner.Name != null ? a.Owner.Name : '') +'"');
            l_fieldValues.add('"'+(a.CurrencyIsoCode != null ? a.CurrencyIsoCode : '')+'"');
            l_fieldValues.add('"'+(a.VAT_Number__c != null ? a.VAT_Number__c : '')+'"');
            l_fieldValues.add('"'+(a.Registered_Number__c != null ? a.Registered_Number__c : '')+'"');
            l_fieldValues.add('"'+a.Id+'"');
            l_fieldValues.add('"'+(a.Notes__c != null ? a.Notes__c : '')+'"');
            l_fieldValues.add('"'+(a.Invoice_Emails__c != null ? a.Invoice_Emails__c : '')+'"');
            recordString+=String.escapeSingleQuotes(String.join(l_fieldValues, ',')+'\n');
        }
        Datetime myDT = Datetime.now().addMonths(-1);
        String dateStr = myDT.format('MMMM YYYY');
        finalstr = finalstr+recordString;
        Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
        blob csvBlob = Blob.valueOf(finalstr);
        string csvname= 'BillingReport'+dateStr+'.csv';
        csvAttc.setFileName(csvname);
        csvAttc.setBody(csvBlob);
        Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();
        List<String> l_emails = new List<String>();
        Admin_Setting__c setting =  Admin_Setting__c.getOrgDefaults();
        if (setting != null && String.isNotBlank(setting.Billing_Emails__c)) {
            l_emails.addAll(setting.Billing_Emails__c.split(';'));
        }
        if (l_emails.size() == 0) {
            l_emails.add(UserInfo.getUserEmail());
        }
        String subject ='Billing Report '+dateStr;
        email.setSubject(subject);
        email.setToAddresses( l_emails );
        email.setPlainTextBody('Billing Report Results for '+dateStr);
        email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
    }
}