force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <inlineHelpText>Contract signed with client</inlineHelpText>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contract_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>TPSA</fullName>
            </value>
            <value>
                <fullName>PMSA</fullName>
            </value>
            <value>
                <fullName>PPRM</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <inlineHelpText>Large Enterprise (&gt;100 employees)
Medium Enterprise (50-100 employees)
Small Enterprise (10-50 employees)
Startup (1-10 employees)</inlineHelpText>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Enterprise</fullName>
            </value>
            <value>
                <fullName>Medium Enterprise</fullName>
            </value>
            <value>
                <fullName>Small Enterprise</fullName>
            </value>
            <value>
                <fullName>Startup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <label>Account Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
                <default>true</default>
                <label>Tier 3</label>
            </value>
            <value>
                <fullName>x Other</fullName>
                <label>Tier X</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>Populated date from activated contract</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Finance_charge_terms_code__c.field-meta.xml
<CustomField>
    <fullName>Finance_charge_terms_code__c</fullName>
    <label>Finance charge terms code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
                <default>true</default>
                <label>3</label>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lock_status__c.field-meta.xml
<CustomField>
    <fullName>Lock_status__c</fullName>
    <label>Lock status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Not Locked</fullName>
            </value>
            <value>
                <fullName>Billing Automated</fullName>
                <isActive>false</isActive>
                <label>Billing Automated</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NavisionID__c.field-meta.xml
<CustomField>
    <fullName>NavisionID__c</fullName>
    <externalId>true</externalId>
    <label>Navision ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registered_Number__c.field-meta.xml
<CustomField>
    <fullName>Registered_Number__c</fullName>
    <inlineHelpText>Please enter the registered number for Contract purposes.</inlineHelpText>
    <label>Registered Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <inlineHelpText>Prospect – new customer
Trial agreement – in a test phase with no MSA signed
Signed – not yet spending
Active – contract signed and spending
Inactive – contract signed, not spending anymore
Rejected – not under contract due to legal or other reasons</inlineHelpText>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Trial Agreement</fullName>
            </value>
            <value>
                <fullName>On Contract</fullName>
                <label>Signed</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Creative Agency</fullName>
            </value>
            <value>
                <fullName>Consultancy Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Standalone Agency</fullName>
            </value>
            <value>
                <fullName>Trading Desk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reminder_terms_code__c.field-meta.xml
<CustomField>
    <fullName>Reminder_terms_code__c</fullName>
    <label>Reminder terms code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>2</label>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_GHG__c.field-meta.xml
<CustomField>
    <fullName>Type_of_GHG__c</fullName>
    <inlineHelpText>Applicable only if contractual relationship in place</inlineHelpText>
    <label>Part of GHG</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Dentsu Aegis Network</fullName>
            </value>
            <value>
                <fullName>Havas</fullName>
            </value>
            <value>
                <fullName>Omnicom Media Group</fullName>
            </value>
            <value>
                <fullName>IPG Mediabrands</fullName>
            </value>
            <value>
                <fullName>Publicis</fullName>
            </value>
            <value>
                <fullName>WPP</fullName>
            </value>
            <value>
                <fullName>Local Planet</fullName>
            </value>
            <value>
                <fullName>Other Global Partners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <inlineHelpText>Please enter the VAT Number for Contract prurposes</inlineHelpText>
    <label>VAT Number / Sales Tax</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Agreement_type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_type__c</fullName>
    <label>Agreement type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MSA</fullName>
                <default>true</default>
                <label>MSA</label>
            </value>
            <value>
                <fullName>BMSA</fullName>
            </value>
            <value>
                <fullName>VS</fullName>
            </value>
            <value>
                <fullName>PMP</fullName>
                <isActive>false</isActive>
                <label>PMP</label>
            </value>
            <value>
                <fullName>PSA</fullName>
                <isActive>false</isActive>
                <label>PSA</label>
            </value>
            <value>
                <fullName>RTB</fullName>
                <isActive>false</isActive>
                <label>RTB</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Effective_date__c.field-meta.xml
<CustomField>
    <fullName>Effective_date__c</fullName>
    <inlineHelpText>Select only 1st day of the month</inlineHelpText>
    <label>Effective date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Package_Size__c.field-meta.xml
<CustomField>
    <fullName>Package_Size__c</fullName>
    <label>Package Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S/M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/VAT_number__c.field-meta.xml
<CustomField>
    <fullName>VAT_number__c</fullName>
    <label>VAT Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Competitor__c</fullName>
    <label>Primary Competitor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Determined</fullName>
                <default>true</default>
                <label>Not Yet Determined</label>
            </value>
            <value>
                <fullName>Appnexus</fullName>
            </value>
            <value>
                <fullName>DataXu</fullName>
            </value>
            <value>
                <fullName>Doubleclick</fullName>
            </value>
            <value>
                <fullName>Flashtalking</fullName>
            </value>
            <value>
                <fullName>Mediamath</fullName>
            </value>
            <value>
                <fullName>Sizmek</fullName>
            </value>
            <value>
                <fullName>Turn</fullName>
            </value>
            <value>
                <fullName>Undertone</fullName>
            </value>
            <value>
                <fullName>Rubicon</fullName>
            </value>
            <value>
                <fullName>Pubmatic</fullName>
            </value>
            <value>
                <fullName>Improve Digital</fullName>
            </value>
            <value>
                <fullName>Adtech</fullName>
            </value>
            <value>
                <fullName>Smart</fullName>
            </value>
            <value>
                <fullName>Adition</fullName>
            </value>
            <value>
                <fullName>OpenX</fullName>
            </value>
            <value>
                <fullName>AdSlot</fullName>
            </value>
            <value>
                <fullName>iSocket</fullName>
            </value>
            <value>
                <fullName>ShinyAds</fullName>
            </value>
            <value>
                <fullName>Enreach</fullName>
            </value>
            <value>
                <fullName>The ADEX</fullName>
            </value>
            <value>
                <fullName>Krux</fullName>
            </value>
            <value>
                <fullName>Relay42</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MigrationServicesControllerTest.cls
@isTest
private class MigrationServicesControllerTest{

    @testSetup
    static void initData(){
        Account acc = new Account(
            Name = 'AccountName',
            Type_of_GHG__c = 'Dentsu Aegis Network',
            Relationship_Type__c = 'Agency',
            Relationship_Status__c = 'Prospect',
            Company_Type__c = 'Large Enterprise',
            CurrencyIsoCode = 'EUR',
            Legal_Company_Name__c = 'AccountName',
            NavisionID__c = '11111',
            Account_Status__c = 'Active',
            Lock_status__c = 'Not Locked',
            Customer_Tier__c = 'Tier 1',
            BillingCountry = 'Germany',
            BillingStreet = 'Billing Street',
            BillingCity = 'Billing City',
            BillingPostalCode = '2222',
            ShippingCountry = 'Germany',
            ShippingStreet = 'Billing Street',
            ShippingCity = 'Billing City',
            ShippingPostalCode = '2222',
            Contract_Status__c = 'Active',
            Agreement_Type__c = 'TPSA',
            VAT_Number__c = '100000',
            Registered_Number__c = '100000000',
            Reminder_terms_code__c = '2',
            Finance_charge_terms_code__c = '3'
        );
        insert acc;
        
        Opportunity opp = new Opportunity(
            Name = 'OpportunityName',
            AccountId = acc.Id,
            Primary_Competitor__c = 'Not Yet Determined',
            StageName = 'Initial Discussion',
            CloseDate = System.today().addYears(1),
            CurrencyIsoCode = acc.CurrencyIsoCode
        );
        insert opp;
    }

    static testMethod void runPositiveTestCase(){
        Opportunity o = [SELECT Id FROM Opportunity WHERE Name = 'OpportunityName' AND StageName = 'Initial Discussion'];
        Test.startTest();
        PageReference myVfPage = Page.MigrationServices;
        Test.setCurrentPage(myVfPage);
        ApexPages.currentPage().getParameters().put('oppId', o.Id);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(new Contract());
        
        MigrationServicesController msc = new MigrationServicesController(stdController);
        msc.contract.Effective_Date__c = date.newinstance(Date.today().addyears(2).year(), 1, 1);
        msc.contract.Package_Size__c = 'L';
        msc.contract.Migration_Model__c = 'Hybrid 1';
        msc.saveAction();
        Contract c = [SELECT Id, Package_Size__c, Migration_Model__c FROM Contract WHERE Id = :msc.contract.Id];
        System.assert(c.Package_Size__c == 'L');
        Test.stopTest();
    }
}