force-app/main/default/objects/Account/fields/Automated_Billing__c.field-meta.xml
<CustomField>
    <fullName>Automated_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automated Billing (at least 1 service)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Highest_Payment_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>Highest_Payment_Terms_Code__c</fullName>
    <label>Highest Payment Terms Code</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Invoicing_period__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_period__c</fullName>
    <defaultValue>&quot;monthly&quot;</defaultValue>
    <label>Invoicing Period</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Is_Approval_Needed_For_Payment_terms__c.field-meta.xml
<CustomField>
    <fullName>Is_Approval_Needed_For_Payment_terms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approval Needed For Payment terms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Minimum_Fee_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Fee_Period__c</fullName>
    <label>Minimum Fee Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Total_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Total_Payment_Terms__c</fullName>
    <label>Total Payment Terms</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/BMSA.recordType-meta.xml
<RecordType>
    <fullName>BMSA</fullName>
    <active>true</active>
    <description>TPAS, DSP and related services</description>
    <label>BMSA</label>
</RecordType>

force-app/main/default/objects/Invoice_Template__c/Invoice_Template__c.object-meta.xml
<CustomObject>
    <label>Invoice Template</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Invoice Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Template__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Automated_Billing__c.field-meta.xml
<CustomField>
    <fullName>Automated_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automated Billing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>Invoice Template</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Master Data</fullName>
            </value>
            <value>
                <fullName>RTB</fullName>
            </value>
            <value>
                <fullName>SE Integrations</fullName>
            </value>
            <value>
                <fullName>TPAS</fullName>
            </value>
            <value>
                <fullName>Pixel Apps</fullName>
            </value>
            <value>
                <fullName>Creative service</fullName>
            </value>
            <value>
                <fullName>Minimum Fee</fullName>
            </value>
            <value>
                <fullName>INTERNAL</fullName>
            </value>
            <value>
                <fullName>RTB Own Inventory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Invoicing_Period__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Period__c</fullName>
    <label>Invoicing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>On Campaign End</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Is_Payment_Terms_Higher__c.field-meta.xml
<CustomField>
    <fullName>Is_Payment_Terms_Higher__c</fullName>
    <formula>AND(NOT(ISNULL(Payment_Term__c)), Contract__r.RecordType.Name = &#39;BMSA&#39;, VALUE(TEXT(Payment_Terms_Code__c)) &gt; VALUE(TEXT(Payment_Term__r.Maximum_Payment_Terms__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Payment Terms Higher</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Payment_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms_Code__c</fullName>
    <label>Payment Terms Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>L0</fullName>
            </value>
            <value>
                <fullName>L1</fullName>
            </value>
            <value>
                <fullName>L10</fullName>
            </value>
            <value>
                <fullName>L15</fullName>
            </value>
            <value>
                <fullName>L20</fullName>
            </value>
            <value>
                <fullName>L25</fullName>
            </value>
            <value>
                <fullName>L30</fullName>
            </value>
            <value>
                <fullName>L60</fullName>
            </value>
            <value>
                <fullName>L90</fullName>
            </value>
            <value>
                <fullName>M0</fullName>
            </value>
            <value>
                <fullName>M10</fullName>
            </value>
            <value>
                <fullName>M105</fullName>
            </value>
            <value>
                <fullName>M11</fullName>
            </value>
            <value>
                <fullName>M120</fullName>
            </value>
            <value>
                <fullName>M13</fullName>
            </value>
            <value>
                <fullName>M14</fullName>
            </value>
            <value>
                <fullName>M15</fullName>
            </value>
            <value>
                <fullName>M18</fullName>
            </value>
            <value>
                <fullName>M20</fullName>
            </value>
            <value>
                <fullName>M21</fullName>
            </value>
            <value>
                <fullName>M22</fullName>
            </value>
            <value>
                <fullName>M25</fullName>
            </value>
            <value>
                <fullName>M28</fullName>
            </value>
            <value>
                <fullName>M3</fullName>
            </value>
            <value>
                <fullName>M30</fullName>
            </value>
            <value>
                <fullName>M33</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceTemplateTriggerHandler.cls
public class InvoiceTemplateTriggerHandler {
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    public InvoiceTemplateTriggerHandler (boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }

    public void OnAfterInsert(List<Invoice_Template__c> l_new) {
        Set<Id> s_ids = new Set<Id>(); 
        Set<Id> s_accids = new Set<Id>(); 
        for(Invoice_Template__c item : l_new) {
            if (item.Contract__c != null) {
                s_ids.add(item.Contract__c);
            }
            if (item.Account__c != null) {
                s_accids.add(item.Account__c);
            }
        }
        updateContract(s_ids);
        //updateAccounts(s_accids);
    }

   
    
    public void OnAfterUpdate(List<Invoice_Template__c> l_old,List<Invoice_Template__c> l_new, Map<Id, Invoice_Template__c> m_new, Map<Id, Invoice_Template__c> m_old ){
        Set<Id> s_ids = new Set<Id>(); 
        Set<Id> s_accids = new Set<Id>();
        String minimumFeePeriod;
        for(Invoice_Template__c item : l_new) {
            Invoice_Template__c oldrec = m_old.get(item.Id);
            if (item.Contract__c != null) {
                s_ids.add(item.Contract__c);
            }
            if (item.Account__c != null) {
                s_accids.add(item.Account__c);
            }
            if(item.File_Type__c == 'Minimum Fee'){
                minimumFeePeriod = item.Invoicing_Period__c;
            }
        }
        updateContract(s_ids);
        updateContractMinimumFeePeriod(s_ids, minimumFeePeriod);
        //updateAccounts(s_accids);
    }
    
    
    public void OnAfterDelete(List<Invoice_Template__c> l_old){
        Set<Id> s_ids = new Set<Id>();
        Set<Id> s_accids = new Set<Id>();
        for(Invoice_Template__c item : l_old) {
            if (item.Contract__c != null) {
                s_ids.add(item.Contract__c);
            }
            if (item.Account__c != null) {
                s_accids.add(item.Account__c);
            }
        }
        updateContract(s_ids);
        //updateAccounts(s_accids);
    }

    public static void updateAccounts(Set<Id> s_ids) {
        List<Account> l_accounts = new List<Account>();
        for(Id sId : s_ids) {
            l_accounts.add(new Account(Id = sId));
        }
        update l_accounts;
    }
    public static void updateContract(Set<Id> s_ids){
        if(s_ids.size() > 0){
            List<Contract> l_contracts = [SELECT Id, Highest_Payment_Terms_Code__c,AccountId, (SELECT Id, Payment_Terms_Code__c, Automated_Billing__c, End_Date__c, Is_Payment_Terms_Higher__c FROM Invoice_Templates__r) FROM  Contract WHERE Id IN:s_ids ];
            Map<Id, Account> m_accounts = new Map<Id, Account>();
            for(Contract c : l_contracts) {
                Boolean isUpdateNeeded = false;
                Decimal highestValue = null;
                Decimal totalPaymentTerms = 0;
                Boolean isPaymentTermsHigher = false;
                Boolean isAutomatedBilling = false;
                for(Invoice_Template__c it : c.Invoice_Templates__r) {
                    if (it.End_Date__c == null) {
                        isUpdateNeeded = true;
                        Decimal value = 0;
                        try{
                            value = decimal.valueOf(it.Payment_Terms_Code__c);
                        }
                        catch (Exception e){}
                        if (highestValue == null || highestValue < value) {
                            highestValue = value;
                        }
                        if(value != null){
                            totalPaymentTerms += value;
                        }
                        if(it.Is_Payment_Terms_Higher__c){
                            isPaymentTermsHigher = it.Is_Payment_Terms_Higher__c;
                        }
                    }
                    if (it.Automated_Billing__c) {
                        isAutomatedBilling = it.Automated_Billing__c;
                    }
                }
                if (isUpdateNeeded) {
                    c.Highest_Payment_Terms_Code__c = highestValue;
                    c.Total_Payment_Terms__c = totalPaymentTerms;
                    c.Is_Approval_Needed_For_Payment_terms__c = isPaymentTermsHigher;
                }
                if(isAutomatedBilling) {
                    m_accounts.put(c.AccountId, new Account(Id = c.AccountId, Automated_Billing__c = isAutomatedBilling));
                }
            }
            update l_contracts;
            if (m_accounts.size() > 0) {
                update m_accounts.values();
            }    
        }
    }
    
    public static void updateContractMinimumFeePeriod(Set<Id> s_contractIds, String minimumFeePeriod){
        if(s_contractIds.size() > 0 && minimumFeePeriod != null){
            String recordType;
            List<Contract> l_contracts = [SELECT Id, Minimum_Fee_Period__c, RecordType.DeveloperName FROM Contract WHERE Id IN :s_contractIds];
            for(Contract c : l_contracts){
                recordType = c.RecordType.DeveloperName;
                c.Minimum_Fee_Period__c = minimumFeePeriod;
            }
            if(recordType.equals('BMSA')){
                update l_contracts;
            }
        }
    }
}