force-app/main/default/objects/Account/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <inlineHelpText>When Account Type is Brand/Advertiser, populate this field with the Brand Name.</inlineHelpText>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <inlineHelpText>Large Enterprise (&gt;100 employees)
Medium Enterprise (50-100 employees)
Small Enterprise (10-50 employees)
Startup (1-10 employees)</inlineHelpText>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Enterprise</fullName>
            </value>
            <value>
                <fullName>Medium Enterprise</fullName>
            </value>
            <value>
                <fullName>Small Enterprise</fullName>
            </value>
            <value>
                <fullName>Startup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <label>Account Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
                <default>true</default>
                <label>Tier 3</label>
            </value>
            <value>
                <fullName>x Other</fullName>
                <label>Tier X</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_From_Lead__c.field-meta.xml
<CustomField>
    <fullName>Is_From_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is From Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Creative Agency</fullName>
            </value>
            <value>
                <fullName>Consultancy Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Standalone Agency</fullName>
            </value>
            <value>
                <fullName>Trading Desk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Resource__c/Billing_Resource__c.object-meta.xml
<CustomObject>
    <label>Billing Resource</label>
    <nameField>
        <label>Billing Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Resource__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Payment_terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_terms__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Payment Terms (No. of days)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/Invoice_Template__c.object-meta.xml
<CustomObject>
    <label>Invoice Template</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Invoice Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Template__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Multiple_Billing_Resource__c/Multiple_Billing_Resource__c.object-meta.xml
<CustomObject>
    <label>Multiple Billing Resource</label>
    <nameField>
        <label>Multiple Billing Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Multiple Billing Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Multiple_Billing_Resource__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Multiple Billing Resources</relationshipLabel>
    <relationshipName>Multiple_Billing_Resources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_From__c.field-meta.xml
<CustomField>
    <fullName>Start_From__c</fullName>
    <inlineHelpText>First month of revenue generation</inlineHelpText>
    <label>Expected start month for revenue</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_for_Fees_Calculation_model__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Fees_Calculation_model__c</fullName>
    <label>Available for Fees Calculation model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Included Fees</fullName>
            </value>
            <value>
                <fullName>On Top Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Available_For_Pricing_Model__c.field-meta.xml
<CustomField>
    <fullName>Available_For_Pricing_Model__c</fullName>
    <label>Available For Pricing Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activity Based</fullName>
            </value>
            <value>
                <fullName>Net Amount</fullName>
            </value>
            <value>
                <fullName>Pure media + Data</fullName>
            </value>
            <value>
                <fullName>Gross Platform Spend</fullName>
            </value>
            <value>
                <fullName>Pure Media</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Available_for_Pricing_model__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Pricing_model__c</fullName>
    <label>Selected Pricing Models</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Show_Pricing_Models__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Pricing_Model</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Default_Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Default_Payment_Term__c</fullName>
    <label>Default Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Show_Payment_Terms__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Default_Pricing_Model__c.field-meta.xml
<CustomField>
    <fullName>Default_Pricing_Model__c</fullName>
    <label>Default Pricing Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Show_Pricing_Models__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Pricing_Model</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Default_Selected_Fees__c.field-meta.xml
<CustomField>
    <fullName>Default_Selected_Fees__c</fullName>
    <label>Default Selected Fees</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Selected_Fees_Calculation_model</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Information_Section_Label__c.field-meta.xml
<CustomField>
    <fullName>Information_Section_Label__c</fullName>
    <defaultValue>&#39;Pricing Details&#39;</defaultValue>
    <label>Information Section Label</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Show_Payment_Terms__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Print_Out_Label__c.field-meta.xml
<CustomField>
    <fullName>Print_Out_Label__c</fullName>
    <label>Print Out Label</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Products_Section_Label__c.field-meta.xml
<CustomField>
    <fullName>Products_Section_Label__c</fullName>
    <defaultValue>&#39;Pricing Rates&#39;</defaultValue>
    <label>Products Section Label</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Selected_Fees_Calculation_model__c.field-meta.xml
<CustomField>
    <fullName>Selected_Fees_Calculation_model__c</fullName>
    <label>Selected Fees Calculation model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Selected_Fees_Calculation_model</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Show_Invoice_Details__c.field-meta.xml
<CustomField>
    <fullName>Show_Invoice_Details__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show Invoice Details</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Show_Invoice_Level__c.field-meta.xml
<CustomField>
    <fullName>Show_Invoice_Level__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show Invoice Level</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Show_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Show_Payment_Terms__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show Payment Terms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Show_Pricing_Models__c.field-meta.xml
<CustomField>
    <fullName>Show_Pricing_Models__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show Pricing Models</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/Product_Price__c.object-meta.xml
<CustomObject>
    <label>Product Price</label>
    <nameField>
        <label>Product Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/recordTypes/Currency.recordType-meta.xml
<RecordType>
    <fullName>Currency</fullName>
    <active>true</active>
    <label>Currency</label>
</RecordType>

force-app/main/default/objects/Product_Price__c/recordTypes/Percent.recordType-meta.xml
<RecordType>
    <fullName>Percent</fullName>
    <active>true</active>
    <label>Percent</label>
</RecordType>

force-app/main/default/globalValueSets/Payment_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>45</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <masterLabel>Payment Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Pricing_Model.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Activity Based</fullName>
    </customValue>
    <customValue>
        <fullName>Net Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Pure media + Data</fullName>
    </customValue>
    <customValue>
        <fullName>Gross Platform Spend</fullName>
    </customValue>
    <customValue>
        <fullName>Pure Media</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Fee</fullName>
    </customValue>
    <masterLabel>Pricing Model</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Selected_Fees_Calculation_model.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Included Fees</fullName>
    </customValue>
    <customValue>
        <fullName>On Top Fees</fullName>
    </customValue>
    <masterLabel>Selected Fees Calculation model</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContractBMSA_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=false)
private class ContractBMSA_Test{
    @testSetup static void SetupMethod() {
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Opportunity; 
        Map<String,Schema.RecordTypeInfo> recordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = recordTypeInfo.get('Agency upsell').getRecordTypeId();
        Account accWithBrandAdvert = new Account(Name ='BrandAdvert', Customer_Tier__c ='Tier 1',CurrencyIsoCode='EUR', Relationship_Type__c ='Brand/Advertiser',Brand_Name__c='test', Company_Type__c ='Startup',Is_From_Lead__c  =true);
        Account accWithPublis = new Account(Name ='Publis', Relationship_Type__c ='Publisher', CurrencyIsoCode='EUR', Customer_Tier__c ='Tier 1', Company_Type__c ='Startup', Is_From_Lead__c  =true);
        insert new List<Account>{accWithBrandAdvert, accWithPublis};
        Opportunity opportunityRecord = new Opportunity();
        opportunityRecord.AccountId = accWithBrandAdvert.Id;
        opportunityRecord.Start_From__c = 'January';
        opportunityRecord.Name = 'new record';
        opportunityRecord.StageName = 'Closed';
        opportunityRecord.CloseDate = Date.Today();
        opportunityRecord.RecordTypeId = rtId;
        insert opportunityRecord;
        Product_Group__c pg = new Product_Group__c();
        pg.Name = 'Adserving';
        pg.Default_Payment_Term__c = '30';
        pg.Default_Pricing_Model__c = 'Pure Media';
        pg.Default_Selected_Fees__c = 'Included Fees';
        pg.Information_Section_Label__c = 'On Top Fees';
        pg.Is_Active__c = true;
        pg.Label__c = 'label';
        pg.Order__c = 1;
        pg.Payment_Terms__c = '15; 30; 45; 60';
        pg.Print_Out_Label__c = 'label';
        pg.Products_Section_Label__c = 'label';
        pg.Selected_Fees_Calculation_model__c = 'Included Fees; On Top Fees';
        pg.Available_for_Pricing_model__c = 'Pure media + Data; Gross Platform Spend; Pure Media';
        pg.Show_Invoice_Details__c = true;
        pg.Show_Invoice_Level__c = true;
        pg.Show_Payment_Terms__c = true;
        pg.Show_Pricing_Models__c = true;
        insert pg;
        Product__c product = new Product__c();
        product.Product_Group__c = pg.Id;
        product.Available_for_Fees_Calculation_model__c = 'Included Fees; On Top Fees';
        product.Available_For_Pricing_Model__c = 'Pure media + Data; Gross Platform Spend; Pure Media';
        product.Help_Text__c = 'test {0}';
        product.Is_Currency_Included__c = true;
        product.Measure__c = '%';
        product.Order__c = 1;
        product.Period_Of_Invoicing__c = 'Monthly';
        product.Name = 'product 1';
        insert product;
        Product__c product2 = new Product__c();
        product2.Product_Group__c = pg.Id;
        product2.Available_for_Fees_Calculation_model__c = 'Included Fees; On Top Fees';
        product2.Available_For_Pricing_Model__c = 'Pure media + Data; Gross Platform Spend; Pure Media';
        product2.Help_Text__c = 'test {0}';
        product2.Is_Currency_Included__c = true;
        product2.Measure__c = '%';
        product2.Order__c = 2;
        product2.Period_Of_Invoicing__c = 'Monthly';
        product2.Name = 'product 2';
        insert product2;
        Schema.DescribeSObjectResult ppSchema = Schema.SObjectType.Product_Price__c; 
        Map<String,Schema.RecordTypeInfo> m_productPriceRT = ppSchema.getRecordTypeInfosByName(); 
        List<Product_Price__c> l_productPrice = new List<Product_Price__c>();
        Product_Price__c pp = new Product_Price__c();
        pp.Product__c = product.Id;
        pp.Available_For_Account_Tier__c = 'Tier 1; Tier 2; Tier 3';
        pp.Country_Group__c = 'UK; DACH; IT; NL/BE; IB; CEE; FI; NO; DK; SE; US; BENEFRUX; Baltics; Poland; Turkey; Czech Republic';
        pp.Minimum_Price_Currency__c = 0.323;
        pp.Price_Currency__c = 0.324;
        pp.RecordTypeId = m_productPriceRT.get('Currency').getRecordTypeId();
        l_productPrice.add(pp);
        Product_Price__c pp2 = new Product_Price__c();
        pp2.Product__c = product2.Id;
        pp2.Available_For_Account_Tier__c = 'Tier 1; Tier 2; Tier 3';
        pp2.Country_Group__c = 'UK; DACH; IT; NL/BE; IB; CEE; FI; NO; DK; SE; US; BENEFRUX; Baltics; Poland; Turkey; Czech Republic';
        pp2.Minimum_Price_Percent__c = 1;
        pp2.Price_Percent__c = 1;
        pp2.RecordTypeId = m_productPriceRT.get('Percent').getRecordTypeId();
        l_productPrice.add(pp2);
        insert l_productPrice;
        Contact con1=new Contact();
        con1.LastName='TestLastname';
        con1.Email='abc.test@yahoo.com';
        con1.AccountId=accWithPublis.Id;
        insert con1;
        Billing_Resource__c br=new Billing_Resource__c();
        br.Name='First BR';
        insert br;
        Multiple_Billing_Resource__c mbr=new Multiple_Billing_Resource__c();
        mbr.Name='TEST';
        mbr.Product__c=product.Id;
        mbr.Main_Billing_Resource__c=false;
        mbr.Billing_Resource__c=br.Id;
        insert mbr;
        Contract_Price__c cp=new Contract_Price__c();
        cp.Price__c=100;
        cp.Account__c=accWithBrandAdvert.Id;
        insert cp;
        Invoice_Template__c it=new Invoice_Template__c();
        it.Payment_Terms_Code__c='15';
        insert it;
    }

    @isTest static void contract_creation() {
        Opportunity opp = [select id from Opportunity limit 1];
        Contract contractTemp = new Contract();
        ApexPages.StandardController stdController = new ApexPages.StandardController(contractTemp);
        Test.startTest();
            ApexPages.currentPage().getParameters().put('oppId',opp.Id);
            RC_MSAContractController controller = new RC_MSAContractController(stdController);
            Product_Group__c pg = [SELECT  ID FROM Product_Group__c LIMIT 1];
            Account acc = [SELECT Id FROM Account LIMIT 1];
            ApexPages.currentPage().getParameters().put('recId',pg.Id);
            ApexPages.currentPage().getParameters().put('priceType','Pure media + Data');
            ApexPages.currentPage().getParameters().put('feeType','Included Fees');
            ApexPages.currentPage().getParameters().put('clone','1');
            ApexPages.currentPage().getParameters().put('variation','1');
            controller.getProducts();
            controller.getProductsByFees();
            controller.saveAction();
            contractTemp = [select id from Contract Limit 1];
            ApexPages.StandardController stdControllernew = new ApexPages.StandardController(contractTemp);
            RC_MSAContractController controllernew = new RC_MSAContractController(stdControllernew);
            RC_BMSAPriceController priceInfo = new RC_BMSAPriceController(stdControllernew);
            RC_InvoiceTemplatesHTMLController componentController = new RC_InvoiceTemplatesHTMLController();
            componentController.ContractId = contractTemp.Id;
            componentController.setContractId(contractTemp.Id);
            componentController.getContractId();
            componentController.getTemplates();
            controllernew.changeAccount();
            Contract_Price__c cp = [SELECT ID,Price__c, Account__c FROM Contract_Price__c WHERE Price__c != null LIMIT 1];
            if(cp!=null) {
                cp.Price__c = 1;
                cp.Account__c = acc.Id;
                update cp;
                delete cp;
            }
            Invoice_Template__c it = [SELECT Id ,Payment_Terms_Code__c FROM Invoice_Template__c LIMIT 1];
            if(it != null){
                it.Payment_Terms_Code__c = '30';
                update it;
                delete it;
                delete contractTemp;
            }
        	Test.stopTest();
    }
}