force-app/main/default/objects/Account/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <inlineHelpText>When Account Type is Brand/Advertiser, populate this field with the Brand Name.</inlineHelpText>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <inlineHelpText>Large Enterprise (&gt;100 employees)
Medium Enterprise (50-100 employees)
Small Enterprise (10-50 employees)
Startup (1-10 employees)</inlineHelpText>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Enterprise</fullName>
            </value>
            <value>
                <fullName>Medium Enterprise</fullName>
            </value>
            <value>
                <fullName>Small Enterprise</fullName>
            </value>
            <value>
                <fullName>Startup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_From_Lead__c.field-meta.xml
<CustomField>
    <fullName>Is_From_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is From Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Creative Agency</fullName>
            </value>
            <value>
                <fullName>Consultancy Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Standalone Agency</fullName>
            </value>
            <value>
                <fullName>Trading Desk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Company_Type_custom__c.field-meta.xml
<CustomField>
    <fullName>Company_Type_custom__c</fullName>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestContactTrigger.cls
@isTest
private class TestContactTrigger {
    
    private static testMethod void testCompanyTypeValue() {
        Account accWithBrandAdvert = new Account(Name ='BrandAdvert', Relationship_Type__c ='Brand/Advertiser',Brand_Name__c='test', Company_Type__c ='Startup',Is_From_Lead__c  =true);
        Account accWithPublis = new Account(Name ='Publis', Relationship_Type__c ='Publisher', Company_Type__c ='Startup', Is_From_Lead__c  =true);
        insert new List<Account>{accWithBrandAdvert, accWithPublis};
            
        Contact con1 = new Contact (LastName ='Singh', AccountId =accWithBrandAdvert.Id);
        con1.MailingCity = 'New York';
		con1.MailingCountryCode = 'US';
		con1.MailingStreet = 'Avenue';
		con1.MailingStateCode = 'NY';
		con1.MailingPostalCode = '12412';
        Test.StartTest();
        insert con1;
        Contact conRecord =[Select AccountId, Company_Type_custom__c from Contact WHERE AccountId =:accWithBrandAdvert.Id];
        System.assertEquals('Advertiser', conRecord.Company_Type_custom__c);
            
        conRecord.AccountId = accWithPublis.Id; 
        update conRecord;
            
        Contact updateRecord =[Select AccountId, Company_Type_custom__c from Contact WHERE AccountId =:accWithPublis.Id];
        System.assertEquals('Publisher', updateRecord.Company_Type_custom__c);
        Account accUpdate =[Select Id, Relationship_Type__c FROM Account WHERE Id =:accWithPublis.Id]; 
        accUpdate.Relationship_Type__c ='Agency';
        update accUpdate;
            
        Contact conWithChange =[Select AccountId, Title, Company_Type_custom__c from Contact WHERE AccountId =:accUpdate.Id];
        conWithChange.Title ='testContact';
        update conWithChange;
       
        Contact conWithChangeTest =[Select AccountId, Title, Company_Type_custom__c from Contact WHERE AccountId =:accUpdate.Id];
        System.assertEquals('Agency', conWithChangeTest.Company_Type_custom__c);
        Test.stopTest();  
    }
}