force-app/main/default/objects/Account/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <inlineHelpText>When Account Type is Brand/Advertiser, populate this field with the Brand Name.</inlineHelpText>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <inlineHelpText>Large Enterprise (&gt;100 employees)
Medium Enterprise (50-100 employees)
Small Enterprise (10-50 employees)
Startup (1-10 employees)</inlineHelpText>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Enterprise</fullName>
            </value>
            <value>
                <fullName>Medium Enterprise</fullName>
            </value>
            <value>
                <fullName>Small Enterprise</fullName>
            </value>
            <value>
                <fullName>Startup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_From_Lead__c.field-meta.xml
<CustomField>
    <fullName>Is_From_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is From Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NavisionID__c.field-meta.xml
<CustomField>
    <fullName>NavisionID__c</fullName>
    <externalId>true</externalId>
    <label>Navision ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Creative Agency</fullName>
            </value>
            <value>
                <fullName>Consultancy Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Standalone Agency</fullName>
            </value>
            <value>
                <fullName>Trading Desk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reminder_Emails__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Emails__c</fullName>
    <label>Reminder Emails</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reminder_Emails_CC__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Emails_CC__c</fullName>
    <label>Reminder Emails CC</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Billing_Resource__c/Billing_Resource__c.object-meta.xml
<CustomObject>
    <label>Billing Resource</label>
    <nameField>
        <label>Billing Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Resource__c/fields/Resource_Number__c.field-meta.xml
<CustomField>
    <fullName>Resource_Number__c</fullName>
    <externalId>true</externalId>
    <label>Resource Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Platform_ID__c.field-meta.xml
<CustomField>
    <fullName>Platform_ID__c</fullName>
    <label>Platform ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Order_Contract.recordType-meta.xml
<RecordType>
    <fullName>Order_Contract</fullName>
    <active>true</active>
    <businessProcess>Creative Production Order</businessProcess>
    <description>Creative Production Order request</description>
    <label>Creative Production Order</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <label>Maximum monthly transaction limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Devices__c.field-meta.xml
<CustomField>
    <fullName>Devices__c</fullName>
    <label>Devices</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/IO.recordType-meta.xml
<RecordType>
    <fullName>IO</fullName>
    <active>true</active>
    <description>Creative Production Order</description>
    <label>Creative Production Order</label>
</RecordType>

force-app/main/default/objects/Contract/recordTypes/MSA.recordType-meta.xml
<RecordType>
    <fullName>MSA</fullName>
    <active>true</active>
    <label>MSA Doxis</label>
</RecordType>

force-app/main/default/objects/Contract_Price__c/Contract_Price__c.object-meta.xml
<CustomObject>
    <label>Contract Price</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Contract Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Price__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Billing_Resource__c.field-meta.xml
<CustomField>
    <fullName>Billing_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Resource</label>
    <referenceTo>Billing_Resource__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Invoice_Template__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Template</label>
    <referenceTo>Invoice_Template__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/Invoice_Template__c.object-meta.xml
<CustomObject>
    <label>Invoice Template</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Invoice Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Template__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Payment_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms_Code__c</fullName>
    <label>Payment Terms Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>L0</fullName>
            </value>
            <value>
                <fullName>L1</fullName>
            </value>
            <value>
                <fullName>L10</fullName>
            </value>
            <value>
                <fullName>L15</fullName>
            </value>
            <value>
                <fullName>L20</fullName>
            </value>
            <value>
                <fullName>L25</fullName>
            </value>
            <value>
                <fullName>L30</fullName>
            </value>
            <value>
                <fullName>L60</fullName>
            </value>
            <value>
                <fullName>L90</fullName>
            </value>
            <value>
                <fullName>M0</fullName>
            </value>
            <value>
                <fullName>M10</fullName>
            </value>
            <value>
                <fullName>M105</fullName>
            </value>
            <value>
                <fullName>M11</fullName>
            </value>
            <value>
                <fullName>M120</fullName>
            </value>
            <value>
                <fullName>M13</fullName>
            </value>
            <value>
                <fullName>M14</fullName>
            </value>
            <value>
                <fullName>M15</fullName>
            </value>
            <value>
                <fullName>M18</fullName>
            </value>
            <value>
                <fullName>M20</fullName>
            </value>
            <value>
                <fullName>M21</fullName>
            </value>
            <value>
                <fullName>M22</fullName>
            </value>
            <value>
                <fullName>M25</fullName>
            </value>
            <value>
                <fullName>M28</fullName>
            </value>
            <value>
                <fullName>M3</fullName>
            </value>
            <value>
                <fullName>M30</fullName>
            </value>
            <value>
                <fullName>M33</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_From__c.field-meta.xml
<CustomField>
    <fullName>Start_From__c</fullName>
    <inlineHelpText>First month of revenue generation</inlineHelpText>
    <label>Expected start month for revenue</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_ID__c/Platform_ID__c.object-meta.xml
<CustomObject>
    <description>Defines Adform Platform ID type and actual number. For billing usage data identification.</description>
    <label>Platform ID</label>
    <nameField>
        <displayFormat>PI-{0000000}</displayFormat>
        <label>Platform ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_ID__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Platform_IDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <label>Account ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/fields/End_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>End_Client_ID__c</fullName>
    <label>End Client ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/fields/User_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>User_Group_ID__c</fullName>
    <label>User Group ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/recordTypes/Account_ID.recordType-meta.xml
<RecordType>
    <fullName>Account_ID</fullName>
    <active>true</active>
    <label>TPAS/DSP ID</label>
</RecordType>

force-app/main/default/objects/Platform_ID__c/recordTypes/End_Client_ID.recordType-meta.xml
<RecordType>
    <fullName>End_Client_ID</fullName>
    <active>true</active>
    <label>End Client ID</label>
</RecordType>

force-app/main/default/objects/Platform_ID__c/recordTypes/Inventory_ID.recordType-meta.xml
<RecordType>
    <fullName>Inventory_ID</fullName>
    <active>true</active>
    <label>Inventory ID</label>
</RecordType>

force-app/main/default/classes/TestBatchSearchTrigger.cls
@isTest
private class TestBatchSearchTrigger {
    // Unit test setup. Create all required data for testing
    @testSetup static void initData() {
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Opportunity; 
        Map<String,Schema.RecordTypeInfo> recordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = recordTypeInfo.get('Agency upsell').getRecordTypeId();
        Schema.DescribeSObjectResult contractSchema = Schema.SObjectType.Contract; 
        Map<String,Schema.RecordTypeInfo> recordTypeInfoContract = contractSchema.getRecordTypeInfosByName(); 
        Id msaRTId = null;
        if (recordTypeInfoContract.get('MSA') != null) {
            msaRTId = recordTypeInfoContract.get('MSA').getRecordTypeId();
        }
        if (recordTypeInfoContract.get('MSA Doxis') != null) {
            msaRTId = recordTypeInfoContract.get('MSA Doxis').getRecordTypeId();
        }
        Account acc = new Account(Name ='BrandAdvert', Relationship_Type__c ='Brand/Advertiser',Brand_Name__c='test', Company_Type__c ='Startup',Is_From_Lead__c  =true);
        acc.BillingCity = 'New York';
        acc.BillingCountryCode = 'US';
        acc.BillingStreet = 'Avenue';
        acc.BillingStateCode = 'NY';
        acc.BillingPostalCode = '12412';
        acc.NavisionId__c = 'NA111';
        acc.Reminder_Emails__c='ab.cd@gmail.com';
        acc.Reminder_Emails_CC__c='abcd.xyz@yahoo.com';
        insert acc;
        List<RecordType> l_recordTypes = [SELECT Id FROM  RecordType WHERE DeveloperName  IN ('Account_ID','End_Client_ID','Inventory_ID')];
        List<Platform_ID__c> l_platforms = new List<Platform_ID__c>();
        for(RecordType item : l_recordTypes) {
          l_platforms.add(new Platform_ID__c(Account__c = acc.Id, Account_ID__c = 1424, User_Group_ID__c = 2412, End_Client_Id__c = 2352, RecordTypeID = item.Id));
        }
        insert l_platforms;
        // insert contract 
        Opportunity opportunityRecord = new Opportunity();
        opportunityRecord.Start_From__c = 'January';
        opportunityRecord.Name = 'new record';
        opportunityRecord.StageName = 'Closed';
        opportunityRecord.CloseDate = Date.Today();
        opportunityRecord.RecordTypeId = rtId;
        insert opportunityRecord;
        Contract contractTemp = new Contract();
        contractTemp.AccountId = acc.Id;
        contractTemp.StartDate = date.today();
        contractTemp.ContractTerm = 6;
        contractTemp.Devices__c = 'Desktop';
        contractTemp.Credit_Limit__c = 9;
        if (msaRTId != null) {
            contractTemp.RecordTypeId = msaRTId;
        }
        insert contractTemp;
        Invoice_Template__c invoiceTemplate = new Invoice_Template__c();
        invoiceTemplate.Account__c = acc.Id;
        invoiceTemplate.Contract__c = contractTemp.Id;
        invoiceTemplate.Payment_Terms_Code__c = '30';
        insert invoiceTemplate;
        //insert new billing resource
        Billing_Resource__c newResource = new Billing_Resource__c(Name = 'Test', Resource_Number__c ='TEST NUMBER');
        insert newResource;
        // insert contract price 
        Contract_Price__c contractPrice = new Contract_Price__c(Contract__c = contractTemp.Id, Invoice_Template__c=invoiceTemplate.Id, Price__c = 121, Billing_Resource__c= newResource.Id);
        insert contractPrice;
        List<Contact> l_contacts = new List<Contact>();
        l_contacts.add(new COntact(firstname = 'test', lastName = 'test' ,Sales_Role__c = 'Invoice Email CC'));
        insert l_contacts;
         
    }
    private static testMethod void testSearchAccount() {
       
        Batch_Search job = new Batch_Search();
        Test.startTest();
        	ID batchprocessid = Database.executeBatch(job,1);
        Test.stopTest();
    }
    private static testMethod void doxisIntegrationTest() {
        Test.startTest();
          RestRequest req = new RestRequest(); 
          RestResponse res = new RestResponse();
          req.requestURI = '/services/apexrest/DoxisIntegration'; //Request URL
          String jsonStr = '{"md_subject": "IT Carat Italia 2017 03 29","md_company": "Adform Aps","md_agreementType": "MSA","md_supplementType": "SDF","md_customer_name": "Carat Italia","md_vat_number": "IT08986330150","md_navisionId": ["NA111"],"md_emails": [""],"md_salesOffice": ["IT"],"md_registrationCountry": "IT","md_admintoolId": ["phit-it-"],"md_effectiveDate": "2017-03-29","md_endDate": "","md_statusDocument": "Active","md_withSLA": "false","md_prepayment": "false","md_fee": "false","md_minfee_effectiveDate": "","md_comments": "","md_id": "854e4178-af46-4036-a4b3-f048348833d2","md_weblink": "http://doxis.adform.zone:8080/webcube/?id=SD0dCOFIDOCUMENTS24854e4178-af46-4036-a4b3-f048348833d2182017-07-31T09:48:16.096Z012&system=Adform&action=showdocument&servername=Adform","md_state": "Exported","md_statecomment": ""}';
          req.requestBody = Blob.valueof(jsonStr);
          req.httpMethod = 'POST';
          RestContext.request = req;
          RestContext.response = res;
          String results = RESTDoxisIntegration.createNewContract();
          Test.stopTest();
    }
    private static testMethod void testCaseCleanUp() {
      Id recordTypeId = [SELECT ID FROM RecordType WHERE DeveloperName = 'Order_Contract'].Id;
      Case caseRec = new Case();
      caseRec.RecordTypeId = recordTypeId;
      caseRec.Subject = 'Test';
      insert caseRec;
       Batch_Cases_cleanup job = new Batch_Cases_cleanup();
        Test.startTest();
            ID batchprocessid = Database.executeBatch(job,1);
        Test.stopTest();
    }
    private static testMethod void testDocumentCleanUp() {

      Document document = new Document();
      document.Body = Blob.valueOf('Some Text');
      document.ContentType = 'application/pdf';
      document.DeveloperName = 'my_document';
      document.IsPublic = true;
      document.Name = '(IO Contract) Document';
      document.FolderId = [SELECT Id FROM Folder where Type = 'Document' LIMIT 1].Id;
      insert document;
       Batch_Documents_cleanup job = new Batch_Documents_cleanup();
        Test.startTest();
            ID batchprocessid = Database.executeBatch(job,1);
        Test.stopTest();
    }

}