force-app/main/default/objects/Account/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <inlineHelpText>When Account Type is Brand/Advertiser, populate this field with the Brand Name.</inlineHelpText>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <inlineHelpText>Large Enterprise (&gt;100 employees)
Medium Enterprise (50-100 employees)
Small Enterprise (10-50 employees)
Startup (1-10 employees)</inlineHelpText>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Enterprise</fullName>
            </value>
            <value>
                <fullName>Medium Enterprise</fullName>
            </value>
            <value>
                <fullName>Small Enterprise</fullName>
            </value>
            <value>
                <fullName>Startup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_From_Lead__c.field-meta.xml
<CustomField>
    <fullName>Is_From_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is From Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Creative Agency</fullName>
            </value>
            <value>
                <fullName>Consultancy Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Standalone Agency</fullName>
            </value>
            <value>
                <fullName>Trading Desk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Admin_Setting__c/Admin_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Admin Setting</label>
</CustomObject>

force-app/main/default/objects/Admin_Setting__c/fields/Billing_Emails__c.field-meta.xml
<CustomField>
    <fullName>Billing_Emails__c</fullName>
    <description>This field used to store emails separated by &quot;;&quot;. These emails will be used in Billing schedule job(send billing report).</description>
    <label>Billing Emails</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/BillingReport_Scheduler_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=false)
private class BillingReport_Scheduler_Test{
    // Unit test setup. Create all required data for testing
    @testSetup static void initData() {
        Account acc = new Account(Name ='BrandAdvert', Relationship_Type__c ='Brand/Advertiser',Brand_Name__c='test', Company_Type__c ='Startup',Is_From_Lead__c  =true);
        acc.BillingCity = 'New York';
        acc.BillingCountryCode = 'US';
        acc.BillingStreet = 'Avenue';
        acc.BillingStateCode = 'NY';
        acc.BillingPostalCode = '12412';
        insert acc;
        Admin_Setting__c setting =  Admin_Setting__c.getOrgDefaults();
        if (setting == null) {
            setting = new Admin_Setting__c();
            setting.Billing_Emails__c = UserInfo.getUserEmail();
        }
        
    }
    /* 
        test that billing report launch succesfully 
    */
    static testmethod void test_BillingReport() {
        String CRON_EXP = '0 0 0 15 3 ? 2022';
        Test.startTest();
         String jobId = System.schedule('Billing Report',
	                            CRON_EXP, 
	                            new BillingReport_Scheduler());
	    Set<String> schdulerJobNames = new Set<String>{'Billing Report'};
	    List<CronTrigger> jobs = [SELECT Id, CronJobDetail.Name, State, NextFireTime FROM CronTrigger where CronJobDetail.Name IN: schdulerJobNames ];
	    System.assert(jobs.size() > 0);
        Test.stopTest();
    }
}