force-app/main/default/objects/Account/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <inlineHelpText>When Account Type is Brand/Advertiser, populate this field with the Brand Name.</inlineHelpText>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <inlineHelpText>Large Enterprise (&gt;100 employees)
Medium Enterprise (50-100 employees)
Small Enterprise (10-50 employees)
Startup (1-10 employees)</inlineHelpText>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Enterprise</fullName>
            </value>
            <value>
                <fullName>Medium Enterprise</fullName>
            </value>
            <value>
                <fullName>Small Enterprise</fullName>
            </value>
            <value>
                <fullName>Startup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>Populated date from activated contract</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_From_Lead__c.field-meta.xml
<CustomField>
    <fullName>Is_From_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is From Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Navision_Base_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Navision_Base_Unit_of_Measure__c</fullName>
    <label>Navision Base Unit of Measure</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUDGET</fullName>
            </value>
            <value>
                <fullName>CAMP.</fullName>
            </value>
            <value>
                <fullName>CLICKS</fullName>
            </value>
            <value>
                <fullName>DAYS</fullName>
            </value>
            <value>
                <fullName>HOURS</fullName>
            </value>
            <value>
                <fullName>IMPR</fullName>
            </value>
            <value>
                <fullName>MONTH</fullName>
            </value>
            <value>
                <fullName>UNIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Creative Agency</fullName>
            </value>
            <value>
                <fullName>Consultancy Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Standalone Agency</fullName>
            </value>
            <value>
                <fullName>Trading Desk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Devices__c.field-meta.xml
<CustomField>
    <fullName>Devices__c</fullName>
    <label>Devices</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Effective_date__c.field-meta.xml
<CustomField>
    <fullName>Effective_date__c</fullName>
    <inlineHelpText>Select only 1st day of the month</inlineHelpText>
    <label>Effective date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Highest_Payment_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>Highest_Payment_Terms_Code__c</fullName>
    <label>Highest Payment Terms Code</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Old_Contract__c.field-meta.xml
<CustomField>
    <fullName>Old_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Old Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>Total price include all type of prices for related contract price record (Percent &amp; currency)</description>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/BMSA.recordType-meta.xml
<RecordType>
    <fullName>BMSA</fullName>
    <active>true</active>
    <description>TPAS, DSP and related services</description>
    <label>BMSA</label>
</RecordType>

force-app/main/default/objects/Contract_Price__c/Contract_Price__c.object-meta.xml
<CustomObject>
    <label>Contract Price</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Contract Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Price__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Starting_Date__c.field-meta.xml
<CustomField>
    <fullName>Starting_Date__c</fullName>
    <label>Starting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Unit_of_Measure_Code__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure_Code__c</fullName>
    <label>Unit of Measure Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_From__c.field-meta.xml
<CustomField>
    <fullName>Start_From__c</fullName>
    <inlineHelpText>First month of revenue generation</inlineHelpText>
    <label>Expected start month for revenue</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_ID__c/Platform_ID__c.object-meta.xml
<CustomObject>
    <description>Defines Adform Platform ID type and actual number. For billing usage data identification.</description>
    <label>Platform ID</label>
    <nameField>
        <displayFormat>PI-{0000000}</displayFormat>
        <label>Platform ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_ID__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Platform_IDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <label>Account ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/fields/End_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>End_Client_ID__c</fullName>
    <label>End Client ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_ID__c/fields/User_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>User_Group_ID__c</fullName>
    <label>User Group ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Triggers_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=false)
private class Triggers_Test{
     @testSetup static void initData() {
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Opportunity; 
        Map<String,Schema.RecordTypeInfo> recordTypeInfo = cfrSchema.getRecordTypeInfosByName();
        Id rtId = recordTypeInfo.get('Agency upsell').getRecordTypeId();
        Account acc = new Account(Name ='BrandAdvert', Relationship_Type__c ='Brand/Advertiser',Brand_Name__c='test', Company_Type__c ='Startup',Is_From_Lead__c  =true);
        acc.BillingCity = 'New York';
        acc.BillingCountryCode = 'US';
        acc.BillingStreet = 'Avenue';
        acc.BillingStateCode = 'NY';
        acc.BillingPostalCode = '12412';
        insert acc;
        Opportunity opportunityRecord = new Opportunity();
        opportunityRecord.AccountId = acc.Id;
        opportunityRecord.Start_From__c = 'January';
        opportunityRecord.Name = 'new record';
        opportunityRecord.StageName = 'Closed';
        opportunityRecord.CloseDate = Date.Today();
        opportunityRecord.RecordTypeId = rtId;
        insert opportunityRecord;
        Schema.DescribeSObjectResult ppSchema = Schema.SObjectType.Contract; 
        Map<String,Schema.RecordTypeInfo> recordTypes_Contract = ppSchema.getRecordTypeInfosByName();
        Contract contract1 = new Contract();
        contract1.AccountId = acc.Id;
        contract1.StartDate = date.today();
        contract1.ContractTerm = 6;
        contract1.Devices__c = 'Desktop';
        contract1.Total_Price__c=200;
        contract1.Highest_Payment_Terms_Code__c=20;
        contract1.Effective_date__c=date.today();
        //contract1.RecordTypeId = recordTypes_Contract.get('BMSA').getRecordTypeId();
        insert contract1;
    }

    static testmethod void test_ContractPriceTriggerHandler() {
        Test.startTest();
            Account acc = [SELECT Id, Navision_Base_Unit_of_Measure__c  FROM Account];
            Contract_Price__c cp = new Contract_Price__c(Unit_of_Measure_Code__c = 'IMPR', Account__c = acc.Id);
            insert cp;
            cp.Unit_of_Measure_Code__c = 'BUDGET';
            update cp;
            delete cp;
            acc = [SELECT Id, Navision_Base_Unit_of_Measure__c  FROM Account];
            System.assert(acc.Navision_Base_Unit_of_Measure__c == null);
        Test.stopTest();
    }

    static testmethod void test_PlatformriggerHandler() {
        Test.startTest();
            Account acc = [SELECT Id, Navision_Base_Unit_of_Measure__c  FROM Account];
            Platform_ID__c record =  new Platform_ID__c(Account__c = acc.Id, Account_ID__c = 1424, User_Group_ID__c = 2412, End_Client_Id__c = 2352);
            insert record;
            record.Account_ID__c = 14123;
            update record;
            delete record;
            acc = [SELECT Id, Navision_Base_Unit_of_Measure__c, LastModifiedDate  FROM Account];
            System.assert(acc.LastModifiedDate.Date() == Date.Today());
        Test.stopTest();
    }
    static testmethod void test_ContractTriggerHandler() {
        Test.startTest();
        Date oldContractEffectiveDate=date.today();
            Account acc = [SELECT Id, Navision_Base_Unit_of_Measure__c  FROM Account];
            Contract con=[SELECT Id,AccountId,StartDate,ContractTerm,Devices__c,Total_Price__c,Highest_Payment_Terms_Code__c,
                        Effective_date__c FROM Contract];
            Contract_Price__c cp = new Contract_Price__c(Unit_of_Measure_Code__c = 'BUDGET', Account__c = acc.Id,Contract__c=con.Id,Starting_Date__c=date.today());
            insert cp;
        	ContractTriggerHandler.updateContractPriceStartingDate(con.Id,oldContractEffectiveDate);
            Contract contractTemp = new Contract();
            contractTemp.AccountId = acc.Id;
            contractTemp.StartDate = date.today();
            contractTemp.ContractTerm = 6;
            contractTemp.Devices__c = 'Desktop';
            contractTemp.Total_Price__c=200;
            contractTemp.Highest_Payment_Terms_Code__c=20;
        	contractTemp.Effective_date__c=date.today();
            insert contractTemp;
            contractTemp.status='Activated';
        	contractTemp.Old_Contract__c=con.Id;
            update contractTemp;
            delete contractTemp;
            acc = [SELECT Id, Navision_Base_Unit_of_Measure__c, LastModifiedDate  FROM Account];
            System.assert(acc.LastModifiedDate.Date() == Date.Today());
        Test.stopTest();
    }
}