force-app/main/default/objects/Account/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>Populated date from activated contract</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pre_payment__c.field-meta.xml
<CustomField>
    <fullName>Pre_payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre-payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Need approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Effective_date__c.field-meta.xml
<CustomField>
    <fullName>Effective_date__c</fullName>
    <inlineHelpText>Select only 1st day of the month</inlineHelpText>
    <label>Effective date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Highest_Payment_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>Highest_Payment_Terms_Code__c</fullName>
    <label>Highest Payment Terms Code</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Invoicing_period__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_period__c</fullName>
    <defaultValue>&quot;monthly&quot;</defaultValue>
    <label>Invoicing Period</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Is_Approval_needed_Contract_prices__c.field-meta.xml
<CustomField>
    <fullName>Is_Approval_needed_Contract_prices__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approval needed(Contract prices)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Is_Approval_Needed_For_Payment_terms__c.field-meta.xml
<CustomField>
    <fullName>Is_Approval_Needed_For_Payment_terms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approval Needed For Payment terms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Minimum_Fee_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Fee_Period__c</fullName>
    <label>Minimum Fee Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Old_Contract__c.field-meta.xml
<CustomField>
    <fullName>Old_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Old Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Pre_payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pre_payment_Amount__c</fullName>
    <label>Pre-payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Total_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Total_Payment_Terms__c</fullName>
    <label>Total Payment Terms</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>Total price include all type of prices for related contract price record (Percent &amp; currency)</description>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/BMSA.recordType-meta.xml
<RecordType>
    <fullName>BMSA</fullName>
    <active>true</active>
    <description>TPAS, DSP and related services</description>
    <label>BMSA</label>
</RecordType>

force-app/main/default/objects/Contract_Price__c/Contract_Price__c.object-meta.xml
<CustomObject>
    <label>Contract Price</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Contract Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Price__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Ending_Date__c.field-meta.xml
<CustomField>
    <fullName>Ending_Date__c</fullName>
    <label>Ending Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Invoice_Template__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Template</label>
    <referenceTo>Invoice_Template__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/ProductCustom__c.field-meta.xml
<CustomField>
    <fullName>ProductCustom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contract Prices</relationshipLabel>
    <relationshipName>Contract_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Price__c/fields/Starting_Date__c.field-meta.xml
<CustomField>
    <fullName>Starting_Date__c</fullName>
    <label>Starting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/Invoice_Template__c.object-meta.xml
<CustomObject>
    <label>Invoice Template</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Invoice Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Template__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>Invoice Template</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Master Data</fullName>
            </value>
            <value>
                <fullName>RTB</fullName>
            </value>
            <value>
                <fullName>SE Integrations</fullName>
            </value>
            <value>
                <fullName>TPAS</fullName>
            </value>
            <value>
                <fullName>Pixel Apps</fullName>
            </value>
            <value>
                <fullName>Creative service</fullName>
            </value>
            <value>
                <fullName>Minimum Fee</fullName>
            </value>
            <value>
                <fullName>INTERNAL</fullName>
            </value>
            <value>
                <fullName>RTB Own Inventory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Invoicing_Period__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Period__c</fullName>
    <label>Invoicing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>On Campaign End</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Template__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Invoice_Template__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Template__c</fullName>
    <label>Invoice Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Master Data</fullName>
            </value>
            <value>
                <fullName>RTB</fullName>
            </value>
            <value>
                <fullName>SE Integrations</fullName>
            </value>
            <value>
                <fullName>TPAS</fullName>
            </value>
            <value>
                <fullName>Pixel Apps</fullName>
            </value>
            <value>
                <fullName>Creative service</fullName>
            </value>
            <value>
                <fullName>Minimum Fee</fullName>
            </value>
            <value>
                <fullName>INTERNAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Invoicing_Period__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Period__c</fullName>
    <label>Invoicing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>On Campaign End</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractTriggerHandler.cls
public class ContractTriggerHandler {
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    public ContractTriggerHandler(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    public void OnAfterInsert(List<Contract> l_new) {
        RecordType rt = [SELECT ID FROM RecordType WHERE DeveloperName = 'BMSA'];
        List<Account> l_accounts = new List<Account>(); 
        Set<Id> s_ids = new Set<Id>();
        for(Contract item : l_new) {
            if (item.AccountId != null && s_ids.contains(item.AccountId) == false) {
                if (item.RecordTypeId == rt.Id && item.Approval_Status__c == 'Approved' && item.Status == 'Activated') {
                    l_accounts.add(new Account(Id = item.AccountId, Pre_payment__c = item.Pre_payment__c, Pre_payment_Amount__c = item.Pre_payment_Amount__c));
                }
                else { 
                    l_accounts.add(new Account(Id = item.AccountId));
                }
                s_ids.add(item.AccountId);
            }
        }
        update l_accounts;
    }

    public void OnBeforeUpdate(List<Contract> l_old, List<Contract> l_new, Map<Id, Contract> m_new, Map<Id, Contract> m_old ){
        Set<Id> s_ids = new Set<Id>();
        Set<Id> s_ownerIds = new Set<Id>();
        for(Contract c : l_new) {
            s_ownerIds.add(c.OwnerId);
        }
        Map<Id, User> m_users = new Map<Id, User>([SELECT ID, ManagerId FROM USER WHERE Id IN : s_ownerIds]);
        for(Contract c : l_new) {
            //c.recalculateFormulas();
            Contract oldRec = m_old.get(c.Id);
            system.debug('====APPROVE ===='+c.Is_Approval_Needed_For_Payment_terms__c);
            System.debug('total price ' + c.Total_Price__c + ' is needed ' + c.Is_Approval_Needed_For_Payment_terms__c);
            if ( c.Total_Price__c != null && c.Highest_Payment_Terms_Code__c  != null) {
                User tempUser = m_users.get(c.OwnerId);
                if (c.Approver__c != oldRec.Approver__c && c.Approver__c == null) {
                    c.Approval_Status__c = 'Approved';
                }
                else {
                    if ((c.Is_Approval_Needed_For_Payment_terms__c && ((c.Is_Approval_Needed_For_Payment_terms__c != oldRec.Is_Approval_Needed_For_Payment_terms__c) ||
                   (c.Approval_Status__c != 'Need approval' && c.Total_Payment_Terms__c != oldRec.Total_Payment_Terms__c)) ) ||
                        (c.Is_Approval_needed_Contract_prices__c && ((c.Is_Approval_needed_Contract_prices__c != oldRec.Is_Approval_needed_Contract_prices__c) || 
                   (c.Approval_Status__c != 'Need approval' && c.Total_Price__c != oldRec.Total_Price__c)))) {
                        c.Approval_Status__c = 'Need approval';
                    }
                    else if (c.Approval_Status__c == null && (c.Is_Approval_Needed_For_Payment_terms__c || c.Is_Approval_needed_Contract_prices__c) ) {
                        c.Approval_Status__c = 'Need approval';
                    }
                    else if (c.Is_Approval_Needed_For_Payment_terms__c == false && c.Is_Approval_needed_Contract_prices__c == false) {
                        c.Approval_Status__c = 'Approved';
                    }
                }

            }
        }
    }
   
    public void OnAfterUpdate(List<Contract> l_old, List<Contract> l_new, Map<Id, Contract> m_new, Map<Id, Contract> m_old){
        RecordType rt = [SELECT ID FROM RecordType WHERE DeveloperName = 'BMSA'];
        List<Account> l_accounts = new List<Account>();
        Set<Id> s_ids = new Set<Id>();
        for(Contract c : l_new) {
            if(c.Status == 'Activated' && c.Old_Contract__c != null){
                List<Invoice_Template__c> l_newInvoiceTemplates = new List<Invoice_Template__c>();
                List<Contract_Price__c> l_newContractPrice = new List<Contract_Price__c>();
                Contract oldContract = [SELECT Id, EndDate FROM Contract WHERE Id = :c.Old_Contract__c];
                List<Invoice_Template__c> l_templates = [SELECT ID, NAME, End_Date__c,
                        (SELECT ID, NAME,Ending_Date__c FROM Contract_Prices__r WHERE Ending_Date__c  = null  ORDER BY ProductCustom__r.Order__c)
                        FROM Invoice_Template__c WHERE Contract__c =:c.Old_Contract__c AND End_Date__c = null ORDER BY Product_Group__r.Order__c];
                for(Invoice_Template__c it : l_templates) {
                    if (c.Effective_date__c != null) {
                        it.End_Date__c = c.Effective_date__c.addDays(-1);
                    }
                    l_newInvoiceTemplates.add(it);
                }
                upsert l_newInvoiceTemplates;
                for(Invoice_Template__c it : l_templates) {
                    for(Contract_Price__c cp : it.Contract_Prices__r) {
                        if (c.Effective_date__c != null) {
                            cp.Ending_Date__c = c.Effective_date__c.addDays(-1);
                        }
                        l_newContractPrice.add(cp);
                    }
                }
                upsert l_newContractPrice;
                if (c.Effective_date__c != null) {
                    oldContract.End_Date__c = c.Effective_date__c.addDays(-1);
                }
                upsert oldContract;
            }
            if (c.AccountId != null && s_ids.contains(c.AccountId) == false) {
                if (c.AccountId != null) {
                    if (c.RecordTypeId == rt.Id && c.Approval_Status__c == 'Approved' && c.Status == 'Activated') {
                        l_accounts.add(new Account(Id = c.AccountId, Pre_payment__c = c.Pre_payment__c, Pre_payment_Amount__c = c.Pre_payment_Amount__c,
                                Effective_Date__c = c.Effective_date__c, Contract_Status__c = 'Active'));
                    }
                    else { 
                        l_accounts.add(new Account(Id = c.AccountId));
                    }
                }
                s_ids.add(c.AccountId);
            }
            System.debug(c.Approval_Status__c + ' approval status');
            if (c.Approval_Status__c == 'Need approval' && m_old.get(c.Id).Approval_Status__c != 'Need approval' && Test.isRunningTest() == false) {
                // Create an approval request for the Complaint
                Approval.ProcessSubmitRequest req =
                new Approval.ProcessSubmitRequest();
                req.setObjectId(c.id);
                // Submit the approval request for the Complaint
                Approval.ProcessResult result =
                Approval.process(req);
            }
            for(Contract old : l_old){
                if(c.Effective_date__c != old.Effective_date__c){
                    updateContractPriceStartingDate(c.Id, old.Effective_date__c);
                }
                if(c.Minimum_Fee_Period__c != old.Minimum_Fee_Period__c){
                    updateInvoiceTemplate(c.Id, 'Minimum Fee');
                }
            }
        }
        update l_accounts;
    }
    
    
    public void OnAfterDelete(List<Contract> l_old){
        List<Account> l_accounts = new List<Account>(); 
        Set<Id> s_ids = new Set<Id>();
        for(Contract item : l_old) {
            if (item.AccountId != null && s_ids.contains(item.AccountId) == false) {
                l_accounts.add(new Account(Id = item.AccountId));
                s_ids.add(item.AccountId);
            }
        }
        update l_accounts;
    }
    
    public static void updateContractPriceStartingDate(Id contractId, Date oldContractEffectiveDate){
        if(contractId != null){
            List<Contract_Price__c> l_cps = new List<Contract_Price__c>();
            List<Contract> l_contracts = [SELECT Id, Effective_date__c, (SELECT Id, Starting_Date__c FROM Contract_Prices__r) FROM Contract WHERE Id = :contractId];
            for(Contract c : l_contracts){
                for(Contract_Price__c cp : c.Contract_Prices__r){
                    if(oldContractEffectiveDate == cp.Starting_Date__c){
                        cp.Starting_Date__c = c.Effective_date__c;
                        l_cps.add(cp);
                    }
                }
            }
            update l_cps;
        }
    }
    
    public static void updateInvoiceTemplate(Id contractId, String invoiceTemplateName){
        if(contractId != null){
            List<Invoice_Template__c> l_its = new List<Invoice_Template__c>();
            List<Contract> l_contracts = [SELECT Id, Minimum_Fee_Period__c, RecordType.DeveloperName, (SELECT Id, File_Type__c FROM Invoice_Templates__r WHERE File_Type__c = :invoiceTemplateName) FROM Contract WHERE Id = :contractId];
            for(Contract c : l_contracts){
                if(c.RecordType.DeveloperName.equals('BMSA')){
                    for(Invoice_Template__c it : c.Invoice_Templates__r){
                        it.Invoicing_Period__c = c.Minimum_Fee_Period__c;
                        l_its.add(it);
                    }
                }
            }
            if(!l_its.isEmpty()){
                update l_its;
            }
        }
    }
}