force-app/main/default/objects/Account/fields/NavisionID__c.field-meta.xml
<CustomField>
    <fullName>NavisionID__c</fullName>
    <externalId>true</externalId>
    <label>Navision ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <inlineHelpText>Please enter the VAT Number for Contract prurposes</inlineHelpText>
    <label>VAT Number / Sales Tax</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Admin_Setting__c/Admin_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Admin Setting</label>
</CustomObject>

force-app/main/default/objects/Admin_Setting__c/fields/Doxis_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Doxis_Account_Id__c</fullName>
    <description>Used to store Doxis Account</description>
    <label>Doxis Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Company_registration_number__c.field-meta.xml
<CustomField>
    <fullName>Company_registration_number__c</fullName>
    <label>Company Registration Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Doxis_Document__c.field-meta.xml
<CustomField>
    <fullName>Doxis_Document__c</fullName>
    <label>Doxis Document</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Doxis_Id__c.field-meta.xml
<CustomField>
    <fullName>Doxis_Id__c</fullName>
    <label>Doxis Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Doxis_Request__c.field-meta.xml
<CustomField>
    <fullName>Doxis_Request__c</fullName>
    <label>Doxis Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract/fields/VAT_number__c.field-meta.xml
<CustomField>
    <fullName>VAT_number__c</fullName>
    <label>VAT Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/MSA.recordType-meta.xml
<RecordType>
    <fullName>MSA</fullName>
    <active>true</active>
    <label>MSA Doxis</label>
</RecordType>

force-app/main/default/classes/RESTDoxisIntegration.cls
@RestResource(urlMapping='/DoxisIntegration/*')
global with sharing class RESTDoxisIntegration {

@HttpPost	 
	global static String createNewContract() {
		RestRequest req = RestContext.request;
		Response doxisResponse = new Response();
		try {
			DoxisContract info =	(DoxisContract) System.JSON.deserialize(req.requestBody.toString(), DoxisContract.class);
			Contract contract = new Contract();
			contract.Doxis_Request__c = req.requestBody.toString();
			List<Account> l_accounts = [SELECT ID FROM Account WHERE NavisionId__c IN : info.md_navisionId];
			List<RecordType> l_recrodTypes = [SELECT ID FROM RecordType WHERE DeveloperName = 'MSA'];
			if (l_accounts.size() > 0) {
				contract.AccountId = l_accounts[0].Id;
			}
			if (contract.AccountId == null) {
				contract.AccountId = Admin_Setting__c.getOrgDefaults().Doxis_Account_Id__c;
			}
			contract.Doxis_Document__c = info.md_weblink;
			contract.Doxis_Id__c = info.md_id;
			if (l_recrodTypes.size() > 0) {
	        	contract.RecordTypeId = l_recrodTypes[0].Id;
			}
	        if (info.ci_invoiceAddress != null) {
	        	contract.BillingCity = info.ci_invoiceAddress.city;
		        contract.BillingCountryCode = info.ci_invoiceAddress.countryCode; 
		        contract.BillingPostalCode = info.ci_invoiceAddress.postalCode;
		        contract.BillingStateCode = info.ci_invoiceAddress.stateCode;
		        contract.BillingStreet = info.ci_invoiceAddress.street;
	        }
	        
	        if (info.bi_shippingAddress != null) {
	        	contract.ShippingCity = info.bi_shippingAddress.city;
		        contract.ShippingCountryCode = info.bi_shippingAddress.countryCode;
		        contract.ShippingPostalCode = info.bi_shippingAddress.postalCode;
		        contract.ShippingStateCode = info.bi_shippingAddress.stateCode;
		        contract.ShippingStreet = info.bi_shippingAddress.street;
	        }
	        
	        contract.Company_registration_number__c = info.ci_company_registration_number;
	        contract.VAT_number__c = info.ci_vat_number;
    		insert contract;
    		doxisResponse.contractId = contract.Id;
    		doxisResponse.status = 'Success';
			
		}
		catch (exception ex){
    		doxisResponse.status = 'Failed';
    		doxisResponse.errorMessage =  ex.getMessage();
		} 
		
		return JSON.serialize(doxisResponse);
	}
	
	public class Response {
		public Id contractId;
		public String status;
		public String errorMessage;
	}
}