force-app/main/default/objects/Account/fields/Registered_Number__c.field-meta.xml
<CustomField>
    <fullName>Registered_Number__c</fullName>
    <inlineHelpText>Please enter the registered number for Contract purposes.</inlineHelpText>
    <label>Registered Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <inlineHelpText>Please enter the VAT Number for Contract prurposes</inlineHelpText>
    <label>VAT Number / Sales Tax</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/VAT_number__c.field-meta.xml
<CustomField>
    <fullName>VAT_number__c</fullName>
    <label>VAT Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/BMSA.recordType-meta.xml
<RecordType>
    <fullName>BMSA</fullName>
    <active>true</active>
    <description>TPAS, DSP and related services</description>
    <label>BMSA</label>
</RecordType>

force-app/main/default/objects/Contract/recordTypes/IO.recordType-meta.xml
<RecordType>
    <fullName>IO</fullName>
    <active>true</active>
    <description>Creative Production Order</description>
    <label>Creative Production Order</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Campaign_Format__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Format__c</fullName>
    <label>Campaign Format</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Aura_OpportunityController.cls
/* 
  * Name    : OpportunityController 
  * Author  : Andrei Pruzan
  * Description   : Class used for lighting compoentns related to Opportunity object
  * Maintenance History: 1/06/2018
  
*/  
public with sharing class Aura_OpportunityController {
    @AuraEnabled
    public static List<RecordType> getRecordTypes(Id recId) {
        return [SELECT id, DeveloperName, Name, Description FROM RecordType WHERE SobjectType= 'Contract' AND isActive= true AND DeveloperName IN ('IO','BMSA')];
    }
    
    @AuraEnabled
    public static Opportunity getOpportunity(Id recId) {
        return [SELECT ID,Name,Account.Name,CurrencyIsoCode, Account.VAT_Number__c,Account.BillingCity, Account.BillingCountry, Account.BillingCountryCode, 
            Account.BillingPostalCode, Account.BillingState, Account.BillingStateCode, Account.BillingStreet,
            Account.Registered_Number__c,Campaign_Format__c, AccountId FROM Opportunity WHERE Id=:recId];
    }
    
    @AuraEnabled
    public static List<Contact> getRelatedContacts(Id recId) {
        return [SELECT Id,Name, Email FROM Contact WHERE AccountId IN (SELECT AccountId FROM Opportunity WHERE Id=: recId)];
    }
   
}