force-app/main/default/objects/Account/fields/Reminder_Emails__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Emails__c</fullName>
    <label>Reminder Emails</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reminder_Emails_CC__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Emails_CC__c</fullName>
    <label>Reminder Emails CC</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Role__c.field-meta.xml
<CustomField>
    <fullName>Sales_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Key Decision Maker</fullName>
                <label>Decision Maker</label>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Media Planner</fullName>
            </value>
            <value>
                <fullName>Trafficker</fullName>
            </value>
            <value>
                <fullName>Partner Product Manager</fullName>
            </value>
            <value>
                <fullName>Partner Developer</fullName>
            </value>
            <value>
                <fullName>Invoicing Person</fullName>
            </value>
            <value>
                <fullName>Signing Person</fullName>
            </value>
            <value>
                <fullName>Specifier</fullName>
            </value>
            <value>
                <fullName>Ratifier</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Invoice Email To</fullName>
            </value>
            <value>
                <fullName>Invoice Email CC</fullName>
            </value>
            <value>
                <fullName>Reminder Email To</fullName>
            </value>
            <value>
                <fullName>Reminder Email CC</fullName>
            </value>
            <value>
                <fullName>Kayako Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Sales_Role__c.field-meta.xml
<CustomField>
    <fullName>Sales_Role__c</fullName>
    <inlineHelpText>What role will this individual play in the potential sale?  Mapped to Contacts on Lead conversion.  Additional Contacts w/ Contact Roles can be added to the sales cycle after Lead conversion.</inlineHelpText>
    <label>Sales Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Key Decision Maker</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch_Search.cls
global class Batch_Search implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful{
    public String batchType = null;
    public Map<Id, Set<Id>> finalresults;
    public Map<Account, List<Account>> finalresultsAcc;
    public Map<Contact, List<Contact>> finalresultsCont;
    public Map<Lead, List<Lead>> finalresultsLead;
    global Database.QueryLocator start(Database.BatchableContext BC){
            return Database.getQueryLocator([SELECT Reminder_Emails__c, Reminder_Emails_CC__c  FROM Account ]); 
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope) {
        List<Account> l_accounts = ( List<Account>) scope;
        List<Contact> l_contacts = new List<Contact>();
        for(Account a: l_accounts) {
            if (a.Reminder_Emails__c != null) {
            List<String> l_emails = a.Reminder_Emails__c.split(';');
              for(String email : l_emails) {
                if (Utilities.validateEmail(email)){ 
                  l_contacts.add(new Contact(Email=email, FirstName ='Reminder', LastName = 'Email', Sales_Role__c='Reminder Email To', AccountId = a.Id));
                }
              }
            }
            if (a.Reminder_Emails_CC__c != null) {
            List<String> l_emails = a.Reminder_Emails_CC__c.split(';');
              for(String email : l_emails) {
              if (Utilities.validateEmail(email)){ 
                l_contacts.add(new Contact(Email=email, FirstName ='Reminder', LastName = 'Email', Sales_Role__c='Reminder Email CC', AccountId = a.Id));
                }
              }
            }
        }
        insert  l_contacts;
    }
    
    global void finish(Database.BatchableContext BC){  
        
    }
}