force-app/main/default/objects/Opportunity/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <inlineHelpText>Default is standard, but if any Opportunity Products attached to this Opportunity have been marked with Terms = &quot;Non-Standard&quot;, this value will be &quot;Non-Standard&quot; for the Opportunity as a whole.</inlineHelpText>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Non-Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_From__c.field-meta.xml
<CustomField>
    <fullName>Start_From__c</fullName>
    <inlineHelpText>First month of revenue generation</inlineHelpText>
    <label>Expected start month for revenue</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>TPSA</fullName>
            </value>
            <value>
                <fullName>IO</fullName>
            </value>
            <value>
                <fullName>PMSA</fullName>
            </value>
            <value>
                <fullName>PPRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Guaranteed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Guaranteed_Revenue__c</fullName>
    <inlineHelpText>Optional field used to define amount of committed revenue</inlineHelpText>
    <label>Guaranteed Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Guaranteed_Revenue_Percent__c.field-meta.xml
<CustomField>
    <fullName>Guaranteed_Revenue_Percent__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Guaranteed Revenue %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Guaranteed_Revenue_Total__c.field-meta.xml
<CustomField>
    <fullName>Guaranteed_Revenue_Total__c</fullName>
    <formula>Guaranteed_Revenue_Percent__c *  UnitPrice</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Guaranteed Revenue Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Incremental_Revenue_Percent__c.field-meta.xml
<CustomField>
    <fullName>Incremental_Revenue_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Incremental Revenue %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Incremental_Revenue_Total__c.field-meta.xml
<CustomField>
    <fullName>Incremental_Revenue_Total__c</fullName>
    <formula>Incremental_Revenue_Percent__c *  UnitPrice</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incremental Revenue Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TPAS</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>DSP</fullName>
            </value>
            <value>
                <fullName>PRM</fullName>
            </value>
            <value>
                <fullName>PMP</fullName>
            </value>
            <value>
                <fullName>DMP</fullName>
            </value>
            <value>
                <fullName>Rich Media</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <label>Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Non-Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X10_month__c.field-meta.xml
<CustomField>
    <fullName>X10_month__c</fullName>
    <label>10 month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X11_month__c.field-meta.xml
<CustomField>
    <fullName>X11_month__c</fullName>
    <label>11 month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X12_month__c.field-meta.xml
<CustomField>
    <fullName>X12_month__c</fullName>
    <label>12 month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X1_Month__c.field-meta.xml
<CustomField>
    <fullName>X1_Month__c</fullName>
    <label>1 Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X2_Month__c.field-meta.xml
<CustomField>
    <fullName>X2_Month__c</fullName>
    <label>2 Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X3_Month__c.field-meta.xml
<CustomField>
    <fullName>X3_Month__c</fullName>
    <label>3 Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X4_month__c.field-meta.xml
<CustomField>
    <fullName>X4_month__c</fullName>
    <label>4 month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X5_Month__c.field-meta.xml
<CustomField>
    <fullName>X5_Month__c</fullName>
    <label>5 Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X6_month__c.field-meta.xml
<CustomField>
    <fullName>X6_month__c</fullName>
    <label>6 month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X7_Month__c.field-meta.xml
<CustomField>
    <fullName>X7_Month__c</fullName>
    <label>7 Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X8_month__c.field-meta.xml
<CustomField>
    <fullName>X8_month__c</fullName>
    <label>8 month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X9_month__c.field-meta.xml
<CustomField>
    <fullName>X9_month__c</fullName>
    <label>9 month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityProductsController.cls
public with sharing class OpportunityProductsController {
    public List<OpportunityLineItem> products { get; set; }
    public Opportunity opportunityRecord { get; set; }
    public List<String> monthValues { get; set; }   
    public List<String> totalValue { get; set; }
    public Map<String, String> headerValues { get; set; }
    public Map<String, String> footerValues {get; set; }
    public CurrencyType defaultCurrencyType;
    public Map<String, CurrencyType> currencyMap;
    public Boolean isDealValueVisible { get; set; }
    public OpportunityProductsController(ApexPages.StandardController con){
        totalValue = new List<String>();
        headerValues = new Map<String,String>();
        footerValues = new Map<String, String>();
        if(!test.isRunningTest()) {
            con.addFields(new List<String>{'Start_From__c','CloseDate','CurrencyIsoCode'});
        }
        this.opportunityRecord = (Opportunity) con.getRecord();
        products = [SELECT X1_Month__c, Product2.Name,X2_Month__c, X3_Month__c, X4_Month__c,X5_Month__c,X6_Month__c,X7_Month__c,X8_Month__c,X9_Month__c,X10_Month__c,X11_Month__c,X12_Month__c,
             CurrencyIsoCode,Contract_Type__c,Guaranteed_Revenue__c,Guaranteed_Revenue_Percent__c,Guaranteed_Revenue_Total__c,Id,Incremental_Revenue_Percent__c,Incremental_Revenue_Total__c,
            ListPrice,Name,OpportunityId,PricebookEntryId,Product2Id,ProductCode,Product__c,Quantity,Terms__c,TotalPrice,UnitPrice FROM OpportunityLineItem WHERE OpportunityId =: opportunityRecord.Id order by X1_Month__c];
        monthValues = new List<String>();
        Integer startMonth = 0;
        if(opportunityRecord.Start_From__c == 'January') {
            startMonth = 1;
        }
        else if(opportunityRecord.Start_From__c == 'February') {
            startMonth = 2;
        }
        else if(opportunityRecord.Start_From__c == 'March') {
            startMonth = 3;
        }
        else if(opportunityRecord.Start_From__c == 'April') {
            startMonth = 4;
        }
        else if(opportunityRecord.Start_From__c == 'May') {
            startMonth = 5;
        }
        else if(opportunityRecord.Start_From__c == 'June') {
            startMonth = 6;
        }
        else if(opportunityRecord.Start_From__c == 'July') {
            startMonth = 7;
        }
        else if(opportunityRecord.Start_From__c == 'August') {
            startMonth = 8;
        }
        else if(opportunityRecord.Start_From__c == 'September') {
            startMonth = 9;
        }
        else if(opportunityRecord.Start_From__c == 'October') {
            startMonth = 10;
        }
        else if(opportunityRecord.Start_From__c == 'November') {
            startMonth = 11;
        }
        else if(opportunityRecord.Start_From__c == 'December') {
            startMonth = 12;
        }
        currencyMap = new Map<String, CurrencyType>();
        List<CurrencyType> currensyType = [SELECT ConversionRate,DecimalPlaces,IsActive,IsCorporate,IsoCode FROM CurrencyType WHERE IsActive = true];
        for(CurrencyType item : currensyType) {
            currencyMap.put(item.IsoCode, item);
            if(item.IsCorporate) {
                defaultCurrencyType = item;
            }
        }
        Datetime newTimeVariable = datetime.newInstance(opportunityRecord.CloseDate.year(), startMonth, 10);
        system.debug('newTimeVariable==='+newTimeVariable);
         system.debug('newTimeVariable==='+newTimeVariable.format('MMM (YY)'));
        monthValues.add(newTimeVariable.format('MMM (YY)'));
        for(integer i=1; i<12;i++) {
             system.debug('newTimeVariable==='+newTimeVariable.addmonths(i));
              system.debug('newTimeVariable==='+newTimeVariable.addmonths(i).format('MMM (YY)'));
            monthValues.add(newTimeVariable.addmonths(i).format('MMM (YY)'));
        }
        Decimal totalVal = 0;
        Decimal Total1 = 0;
        Decimal Total2 = 0;
        Decimal Total3 = 0;
        Decimal Total4 = 0;
        Decimal Total5 = 0;
        Decimal Total6 = 0;
        Decimal Total7 = 0;
        Decimal Total8 = 0;
        Decimal Total9 = 0;
        Decimal Total10 = 0;
        Decimal Total11 = 0;
        Decimal Total12 = 0;
        Decimal Guaranteed_Revenue = 0;
        for(OpportunityLineItem item : products) {
            totalVal = totalVal + ((item.UnitPrice != null) ? item.UnitPrice : 0 );
            Total1 = Total1 + ((item.X1_Month__c != null) ? item.X1_Month__c : 0 );
            Total2 = Total2 + ((item.X2_Month__c != null) ? item.X2_Month__c : 0 );
            Total3 = Total3 + ((item.X3_Month__c != null) ? item.X3_Month__c : 0 );
            Total4 = Total4 + ((item.X4_Month__c != null) ? item.X4_Month__c : 0 );
            Total5 = Total5 + ((item.X5_Month__c != null) ? item.X5_Month__c : 0 );
            Total6 = Total6 + ((item.X6_Month__c != null) ? item.X6_Month__c : 0 );
            Total7 = Total7 + ((item.X7_Month__c != null) ? item.X7_Month__c : 0 );
            Total8 = Total8 + ((item.X8_Month__c != null) ? item.X8_Month__c : 0 );
            Total9 = Total9 + ((item.X9_Month__c != null) ? item.X9_Month__c : 0 );
            Total10 = Total10 + ((item.X10_Month__c != null) ? item.X10_Month__c : 0 );
            Total11 = Total11 + ((item.X11_Month__c != null) ? item.X11_Month__c : 0 );
            Total12 = Total12 + ((item.X12_Month__c != null) ? item.X12_Month__c : 0 );
            Guaranteed_Revenue = Guaranteed_Revenue + ((item.Guaranteed_Revenue__c != null) ? item.Guaranteed_Revenue__c : 0 );
        }
        List<Schema.FieldSetMember> productFields = SObjectType.OpportunityLineItem.FieldSets.Opportunity_Product.getFields();
        Map<String, Schema.SObjectField> FsMap = OpportunityLineItem.sObjectType.getDescribe().fields.getMap();
        for(Schema.FieldSetMember f : productFields) {
            if(f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.UnitPrice.getName()) {
                headerValues.put(f.getFieldPath(),Label.Deal_Value);
                footerValues.put(f.getFieldPath(), prepareTotalValue(totalVal));
            }
            else if (f.getFieldPath() ==Schema.SObjectType.OpportunityLineItem.fields.X1_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[0]);
                footerValues.put(f.getFieldPath(), prepareTotalValue(Total1));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.X2_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[1]);
                footerValues.put(f.getFieldPath(), prepareTotalValue(Total2));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.X3_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[2]);
                footerValues.put(f.getFieldPath(),prepareTotalValue(Total3));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.X4_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[3]);
                footerValues.put(f.getFieldPath(),prepareTotalValue(Total4));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.X5_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[4]);
                footerValues.put(f.getFieldPath(),prepareTotalValue(Total5));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.X6_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[5]);
                footerValues.put(f.getFieldPath(),prepareTotalValue(Total6));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.X7_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[6]);
                footerValues.put(f.getFieldPath(),prepareTotalValue(Total7));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.X8_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[7]);
                footerValues.put(f.getFieldPath(),prepareTotalValue(Total8));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.X9_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[8]);
                footerValues.put(f.getFieldPath(),prepareTotalValue(Total9));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.X10_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[9]);
                footerValues.put(f.getFieldPath(),prepareTotalValue(Total10));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.X11_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[10]);
                footerValues.put(f.getFieldPath(),prepareTotalValue(Total11));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.X12_Month__c.getName()) {
                headerValues.put(f.getFieldPath(),monthValues[11]);
                footerValues.put(f.getFieldPath(),prepareTotalValue(Total12));
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.Product2Id.getName()) {
                headerValues.put(f.getFieldPath(), Product2.sObjectType.getDescribe().getLabel());
                footerValues.put(f.getFieldPath(),'');
            }
            else if (f.getFieldPath() == Schema.SObjectType.OpportunityLineItem.fields.Guaranteed_Revenue__c.getName()) {
                headerValues.put(f.getFieldPath(), FsMap.get(f.getFieldPath()).getDescribe().getLabel());
                footerValues.put(f.getFieldPath(),prepareTotalValue(Guaranteed_Revenue));
            }
            else {
                headerValues.put(f.getFieldPath(), FsMap.get(f.getFieldPath()).getDescribe().getLabel());
                footerValues.put(f.getFieldPath(),'');
            }
            
        }
        
        User loggedInUser = [SELECT Id, UserRoleId FROM User WHERE Id = :UserInfo.getUserId()];
        List<Opportunity> l_opp = [SELECT Owner.Id FROM Opportunity WHERE Id = :opportunityRecord.Id LIMIT 1];
        User recordOwner;
        for(Opportunity opp : l_opp){
            recordOwner = [SELECT UserRoleId FROM User WHERE Id = :opp.OwnerId];
        }
        List<String> l_recSupportedRoles = getRecordSupportedRoles(recordOwner);
        System.debug(l_recSupportedRoles);
        if(recordOwner != null && (l_recSupportedRoles.contains(loggedInUser.UserRoleId) || recordOwner.Id == loggedInUser.Id)){
            this.isDealValueVisible = true;
        } else if(recordOwner == null){
            this.isDealValueVisible = true;
        } else {
            this.isDealValueVisible = false;
        }
    }
    
    public String prepareTotalValue(Decimal totalValue){
        String strTotal = this.opportunityRecord.CurrencyIsoCode+' '+totalValue.format();
        CurrencyType currencyRec = currencyMap.get(this.opportunityRecord.CurrencyIsoCode);
        if(currencyRec != null && currencyRec.IsCorporate == false) {
            Decimal defaultTotal = totalValue/currencyRec.ConversionRate;
            strTotal += ' ('+defaultCurrencyType.IsoCode+' '+defaultTotal.setscale(2).format()+')';
        }
        return strTotal;
    }
    
    public List<String> getRecordSupportedRoles(User recordOwner){
        List<String> l_visibleForRoles = new List<String>();
        if(recordOwner != null){
            UserRole ownerRole;
            ownerRole = [SELECT Id, ParentRoleId FROM UserRole WHERE Id = :recordOwner.UserRoleId];
            String parentRoleId = ownerRole.ParentRoleId;
            UserRole parentRole;
            while(parentRoleId != null){
                parentRole = [SELECT Id, ParentRoleId FROM UserRole WHERE Id = :parentRoleId];
                l_visibleForRoles.add(parentRole.Id);
                parentRoleId = parentRole.ParentRoleId;
            }
        }
        return l_visibleForRoles;
    }
}