force-app/main/default/objects/Contact/fields/Trainings_Completed__c.field-meta.xml
<CustomField>
    <fullName>Trainings_Completed__c</fullName>
    <label>Trainings Completed</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TPAS basic training</fullName>
            </value>
            <value>
                <fullName>RTB basic training</fullName>
            </value>
            <value>
                <fullName>RTB optimization</fullName>
            </value>
            <value>
                <fullName>Site-tracking</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Rich media</fullName>
            </value>
            <value>
                <fullName>HTML5 Studio</fullName>
            </value>
            <value>
                <fullName>Adform Creative Toolkit</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>DCO banners</fullName>
            </value>
            <value>
                <fullName>Dynamic content ads</fullName>
            </value>
            <value>
                <fullName>ABC of programmatic digital media buying</fullName>
            </value>
            <value>
                <fullName>DMP</fullName>
            </value>
            <value>
                <fullName>Adform Support</fullName>
            </value>
            <value>
                <fullName>Tailored Trainings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaskTriggerHandler.cls
public class TaskTriggerHandler {
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;

    public TaskTriggerHandler(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }


    public void OnAfterUpdate(Task[] oldTasks, Task[] newTasks, Map<ID, Task> newMap, Map<Id, Task> oldMap){
        Map<Id, List<String>> m_contactToTraining = new Map<Id, List<String>>();
        Schema.sObjectType  contactObjectType = Schema.Contact.SObjectType;
        for(Task task : newTasks){
            if (task.Training_Type__c != null && task.WhoId != null && task.Status == 'Completed' && task.Status != oldMap.get(task.Id).Status && task.WhoId.getSobjectType() == contactObjectType) {
                    List<String> l_temp = new List<String>();
                        if (m_contactToTraining.containsKey(task.WhoId)) {
                                l_temp = m_contactToTraining.get(task.WhoId);
                        }
                        l_temp.add(task.Training_Type__c);
                        m_contactToTraining.put(task.WhoId,l_temp);
            }   
        }
        if (m_contactToTraining.size() > 0) {
                List<Contact> l_contacts = [SELECT Id, Trainings_Completed__c FROM Contact WHERE Id IN :m_contactToTraining.keySet()];
                for(Contact item : l_contacts) {
                        List<String> l_temp = m_contactToTraining.get(item.Id);
                        if (item.Trainings_Completed__c == null) {
                                item.Trainings_Completed__c = String.join(l_temp,';');
                        }
                        else {
                                item.Trainings_Completed__c = item.Trainings_Completed__c +';'+String.join(l_temp,';');
                        }
                }
                update l_contacts;
        }
        
        
    }

}