force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <inlineHelpText>Please use {0} condition i help text if you want to use minimum price in Help text from product price level, depending  on user country group.</inlineHelpText>
    <label>Help Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Measure__c.field-meta.xml
<CustomField>
    <fullName>Measure__c</fullName>
    <label>Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>%</fullName>
            </value>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>CPC</fullName>
            </value>
            <value>
                <fullName>% from RTB budget spend</fullName>
            </value>
            <value>
                <fullName>Fixed per app install</fullName>
            </value>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>Hour</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>% (adserving cost)</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>KB</fullName>
            </value>
            <value>
                <fullName>Imp</fullName>
            </value>
            <value>
                <fullName>CPM (incremental per MB)</fullName>
            </value>
            <value>
                <fullName>Thousand Impressions</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
            <value>
                <fullName>Thousand Impressions (incremental per each 1,000 KB above 3,000 KB)</fullName>
            </value>
            <value>
                <fullName>Search Engine Costs</fullName>
            </value>
            <value>
                <fullName>Click</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>TPAS fees</fullName>
            </value>
            <value>
                <fullName>TPAS and Third Party Tracking with Adform fees</fullName>
            </value>
            <value>
                <fullName>RTB Service Fee Units indicated above or CPM</fullName>
            </value>
            <value>
                <fullName>Banner Created</fullName>
            </value>
            <value>
                <fullName>Trading Desk Fee</fullName>
            </value>
            <value>
                <fullName>-</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <inlineHelpText>Please use {0} condition in help text if you want to use maximum payment terms in Help text from payment terms level, depending on user country group.</inlineHelpText>
    <label>Help Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Show_Payment_Terms__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Price__c/Product_Price__c.object-meta.xml
<CustomObject>
    <label>Product Price</label>
    <nameField>
        <label>Product Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>45</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <masterLabel>Payment Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RC_TemplateGenerationController.cls
/* 
 * Name          : RC_TemplateGenerationController
 * Author        : Andrei Pruzan
 * Description   : Controller for RC_TemplateGeneration page
 * Visulforce page : RC_TemplateGeneration
 * Unit test : 
 * Maintenance History: 
 * 2017/09/26 - AP - 1.0 - Created. 
*/
public without sharing class RC_TemplateGenerationController {

    public class ProductGroup{
        Public Product_Group__c productGroup { get; set; }
        public List<Product> products { get; set; }
    }
    public class Product  {
        public Product__c product { get; set; }
        public Product_Price__c price { get; set; }
    }
    
    public List<ProductGroup> l_productGroups { get; set; }
    
    public RC_TemplateGenerationController() {
        l_productGroups = new List<ProductGroup>();
        /*List<Product_Group__c> l_obPg = [SELECT ID, Label__c, Payment_Terms__c FROM Product_Group__c WHERE is_active__c = true ORDER BY Order__c];
        List<Product__c> l_obp = [SELECT ID, Name, Product_Group__c, Help_Text__c, Measure__c,
                                (SELECT ID, CurrencyIsoCode, Price__c FROM Product_Prices__r)  
                                 FROM Product__c WHERE Product_Group__c IN :l_obPg  ORDER BY Order__c];
        Map<Id, List<Product__c>> m_productGroups = new Map<Id, List<Product__c>>();
        for(Product__c item : l_obp) {
            List<Product__c> l_temp = new List<Product__c>();
            if (m_productGroups.containsKey(item.Product_Group__c) == true) {
                l_temp = m_productGroups.get(item.Product_Group__c);
            }    
            l_temp.add(item);
            m_productGroups.put(item.Product_Group__c, l_temp);
        }
        
        for(Product_Group__c pg : l_obPg) {
            ProductGroup temppg = new ProductGroup();
            temppg.productGroup = pg;
            List<Product> l_temp = new List<Product>();
            List<Product__c> l_products = m_productGroups.get(pg.Id);
            if (l_products == null) {
                l_products = new List<Product__c> ();
            }
            for(Product__c item : l_products) {
                Product tempp = new Product();
                tempp.product = item;
                if (item.Product_Prices__r.size() > 0) {
                    tempp.price = item.Product_Prices__r[0];
                }
                l_temp.add(tempp);
            }
            temppg.products = l_temp;
            l_productGroups.add(temppg);
        }*/
    }
}