force-app/main/default/objects/Triggers_Settings__c/Triggers_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Triggers Settings</label>
</CustomObject>

force-app/main/default/objects/Triggers_Settings__c/fields/Trigger_name__c.field-meta.xml
<CustomField>
    <fullName>Trigger_name__c</fullName>
    <label>Trigger name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerHandlerGeneralTest.cls
@isTest
private class TriggerHandlerGeneralTest {
    
    @isTest static void testTriggerStopForParticularUser() {
        User firstUser = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        User secondUser = [SELECT Id FROM User WHERE Id != :firstUser.Id AND IsActive = true LIMIT 1];
        insert new Triggers_Settings__c(Name = 'MainObjectTrigger', Trigger_name__c = 'MainObjectTrigger', User_Id__c = firstUser.Id, Is_Active__c = false);

        System.runAs(firstUser) {
            System.assertEquals(false, TriggerHandlerGeneral.isTriggerRun('MainObjectTrigger'));
            System.assertEquals(true, TriggerHandlerGeneral.isTriggerRun('SideObjectTrigger'));
        }

        System.runAs(secondUser) {
            System.assertEquals(true, TriggerHandlerGeneral.isTriggerRun('MainObjectTrigger'));
            System.assertEquals(true, TriggerHandlerGeneral.isTriggerRun('SideObjectTrigger'));
        }       
    }
    
    @isTest static void testTriggerStopForAllUsers() {
        User firstUser = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        User secondUser = [SELECT Id FROM User WHERE Id != :firstUser.Id AND IsActive = true LIMIT 1];
        insert new Triggers_Settings__c(Name = 'MainObjectTrigger', Trigger_name__c = 'MainObjectTrigger', User_Id__c = 'All', Is_Active__c = false);

        System.runAs(firstUser) {
            System.assertEquals(false, TriggerHandlerGeneral.isTriggerRun('MainObjectTrigger'));
            System.assertEquals(true, TriggerHandlerGeneral.isTriggerRun('SideObjectTrigger'));
        }

        System.runAs(secondUser) {
            System.assertEquals(false, TriggerHandlerGeneral.isTriggerRun('MainObjectTrigger'));
            System.assertEquals(true, TriggerHandlerGeneral.isTriggerRun('SideObjectTrigger'));
        }
    }

    
}