force-app/main/default/objects/Triggers_Settings__c/Triggers_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Triggers Settings</label>
</CustomObject>

force-app/main/default/objects/Triggers_Settings__c/fields/Trigger_name__c.field-meta.xml
<CustomField>
    <fullName>Trigger_name__c</fullName>
    <label>Trigger name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerHandlerGeneral.cls
public class TriggerHandlerGeneral {

    private static final List<Triggers_Settings__c> TRIGGERS_SETTINGS = Triggers_Settings__c.getAll().values();

    public static Boolean isTriggerRun(String triggerName) {
        for (Triggers_Settings__c setting : TRIGGERS_SETTINGS) {
            if ((setting.Trigger_name__c.equals(triggerName) || setting.Trigger_name__c.equals('All'))
             && (setting.User_Id__c.equals(UserInfo.getUserId()) || setting.User_Id__c.equals('All'))
             && !setting.Is_Active__c) {
                return false;
            }
        }
        return true;
    }
}